### ISSUE TITLE
Shadows

### ISSUE THREAD

**Issue by talltyler** [phoboslab/Ejecta#132]
How about finishing out the canvas spec? Shadows is the last big feature left in the standard implementation. It is kind of an odd feature because it isn't like anything else, if you rather start on the new filter spec https://dvcs.w3.org/hg/FXTF/raw-file/tip/filters/index.html#feDropShadowElement 
that would be even better but some kind of drop shadow would really help the thing I'm working on.

**Comment by phoboslab** [comment]
Closing this for lack of interest and because it's difficult to implement properly.
