### ISSUE TITLE
Archive name in organizer different than ${PRODUCT_NAME}

### ISSUE THREAD

**Issue by 0plus1** [phoboslab/Ejecta#171]
I'm having an issue that's driving me crazy.

I double checked everything in xcode and ${PRODUCT_NAME} is set correctly in "Build Settings"->"Product Name", I check everywhere my knowledge took me and in Xcode there is no mention anywhere of "Ejecta".

Not only this but the name shown near the "Play-Stop" buttons on the interface is always "Ejecta". Can someone help me understand why? How can I change it to my own string, I don't want to be rejected by Apple for this..

**Comment by ameuret** [comment]
For the record (since this page is highly ranked by Google), the archive name appears in the App Store Connect web site (as "Original File Name"). Not exactly public, but a thin leak anyway.
