### ISSUE TITLE
Font Styling Doesn't Work?

### ISSUE THREAD

**Issue by jessemillar** [phoboslab/Ejecta#195]
According to everything I can find in regards to normal HTML5 canvas elements,

```
ctx.font = "bold 15px Arial";
```

should result in **bold** text of the proper font and size but it doesn't seem to do so in Ejecta.

**Comment by vinhtq** [comment]
@phoboslab Did you include it in the lastest version?
@jessemillar If not can you tell me where should i put your code in?

**Comment by jessemillar** [comment]
@vinhtq I don't believe I actually implemented @finscn's code. It's been three years though, so my recollection could be faulty. Does specifying the full font name (EG: `ctx.font = "15px Arial-BoldMT"`) not work for you?
