### ISSUE TITLE
Support for camera input in WebGL

### ISSUE THREAD

**Issue by darknoon** [phoboslab/Ejecta#217]
I started doing a bit of hacking on getting camera input to work via the WebRTC getUserMedia() API. Code is a bit of a mess, but I got basic camera input rendering with a shader. Is there anyone else interested in making this work?

The current implementation of the <video> element seems at odds with the idea of using it as a the source of a texture in glTexImage2D, so my current changes disable the movie player.

Thoughts?

**Comment by sherbondy** [comment]
I'm interested in taking a swing at this. Not worth re-opening the issue for now, but I'll keep you folks posted if I get a working fork running with reasonable performance.

A small subset (the non-networking bits) of this codebase may be relevant/helpful:
https://github.com/EricssonResearch/OpenWebRTC

They've got a working iOS setup here:
https://github.com/EricssonResearch/openwebrtc-ios-sdk

**Comment by phoboslab** [comment]
I don't think there's much code you could take from the OpenWebRTC project.

For Ejecta, you probably want to continuously grab the camera image and provide it as an OpenGL texture. Similar to the EJBindingImage, but with an automatically updating EJTexture as backing.
