### ISSUE TITLE
how to balance audio in Ejecta  and Will Ejecta support WebAudio API ?

### ISSUE THREAD

**Issue by finscn** [phoboslab/Ejecta#248]
In HTML5, the Audio tag doesn't supply the feature about "audio balance".

But in iOS game , the good sound is very important (with headphone).

how to balance audio in Ejecta ?

Will Ejecta support WebAudio API  in the future ?

**Comment by phoboslab** [comment]
Closing for lack of interest. Going forward, a minimal implementation of the WebAudio API would probably be favorable.
