### ISSUE TITLE
Ejecta as a library

### ISSUE THREAD

**Issue by cga-F4** [phoboslab/Ejecta#327]
I am working on a app, where I want to replace an existing view with a WebGL canvas view using Ejecta.
As for now, Ejecta is an app itself, so I don't know how to include it into my project (I could include all files in my own project, but I will loose the git update or others stuff like this).
Do you plan to turn Ejecta onto a library, so it can be easily be included in another project ? Or tell me if this idea is a bad idea.

**Comment by swannodette** [comment]
@SRandazzo is it possible to get an updated podspec for Ejecta, i.e. 1.5? Thanks.

**Comment by SRandazzo** [comment]
@swannodette Attached below with some important notes!

We're on a slightly older/forked version of Ejecta right now, so i threw this together and tested it. 
The only issue I found is that there appears to be a missing import in `EJCanvasContextWebGLTexture.m` causing some compiler errors. The missing import is: `#import <OpenGLES/ES2/gl.h>`

It appears that in the Ejecta 1.5 tag (I downloaded the zip and attempted to build to confirm it's not my setup), there is just a build error. OpenGLES/ES1 is being imported, but components from OpenGLES/ES2 are being used (GL_FRAMEBUFFER_BINDING and some others), causing a build error.

Your best bet for a temporary workaround is to change `:tag => 'v1.5'` to `:commit => 'the_latest_sha' which should probably work.

Maybe we can get an updated version/tag from @phoboslab and I can PR the podspec back :-D

```
Pod::Spec.new do |s|
  s.name = 'Ejecta'
  s.version = '1.5'
  s.license = 'MIT'
  s.summary = 'A Fast, Open Source JavaScript, Canvas & Audio Implementation for iOS.'
  s.homepage = 'http://impactjs.com/ejecta'
  s.author = { 'Dominic Szablewski' => 'dominic.szablewski@gmail.com' }
  s.source = { :git => 'https://github.com/phoboslab/Ejecta.git', :tag => 'v1.5' }
  s.description = 'A Fast, Open Source JavaScript, Canvas & Audio Implementation for iOS.'
  s.platform = :ios
  s.requires_arc =  false

  s.source_files = 'Source/Ejecta/**/*.{h,m,mm}', 'Source/lib/NSString+*.{h,m}'
  s.resources    = 'Source/Ejecta/ejecta.js', 'Source/Ejecta/EJCanvas/2D/Shaders/*'

  s.default_subspec = 'JavaScriptCore'
  s.frameworks = 'JavaScriptCore', 'SystemConfiguration', 'CoreText', 'QuartzCore', 'GameKit', 'CoreGraphics', 'OpenAL', 'AudioToolbox', 'OpenGLES', 'AVFoundation', 'iAd', 'CoreMotion', 'MediaPlayer', 'CoreLocation'

  s.header_mappings_dir =  'Source/Ejecta'

  s.subspec 'JavaScriptCore' do |os|
    os.source_files = 'Source/lib/JavaScriptCore.framework/Versions/A/Headers/*.h'
    os.preserve_paths = 'Source/lib/JavaScriptCore.framework/*'
    os.library = 'stdc++', 'icucore'
    os.xcconfig = { 'LIBRARY_SEARCH_PATHS' => '"$(PODS_ROOT)/Ejecta/Source/lib"', 'HEADER_SEARCH_PATHS' => '"$(PODS_ROOT)/Ejecta/Source/lib"', 'FRAMEWORK_SEARCH_PATHS' => '"$(PODS_ROOT)/Ejecta/Source/lib"',
 }

    os.header_mappings_dir = 'Source/Ejecta'

    s.xcconfig = {
         'CLANG_CXX_LANGUAGE_STANDARD' => 'gnu++98',
         'CLANG_CXX_LIBRARY' => 'libc++'
    }
  end
end

```

:wave: Also hello from Paperless Post!

**Comment by swannodette** [comment]
@SRandazzo oh man, so awesome! Thank you!!! @phoboslab could we please get another tag? Thanks!
