### ISSUE TITLE
Feature request context.currentTransform

### ISSUE THREAD

**Issue by talltyler** [phoboslab/Ejecta#332]
They've added a new currentTransform property to the context that is quite useful.
http://www.whatwg.org/specs/web-apps/current-work/multipage/the-canvas-element.html#dom-context-2d-currenttransform

I have a polyfill for it now but it would be great if you could just expose this.

Thanks

**Comment by phoboslab** [comment]
This proposal seems to be pretty dead. It's still not implemented in Firefox, Safari or IE and there seems to be little interest in doing so. Closing this issue.
