### ISSUE TITLE
Too many warnings on XCode 5.1 + iOS 7.1

### ISSUE THREAD

**Issue by finscn** [phoboslab/Ejecta#357]
as shown in the screen shoot : 

![2014-03-12 2 51 08](https://f.cloud.github.com/assets/288367/2389477/5794ad0c-a94e-11e3-8000-ee19aa7a7f34.png)

> ld: warning: arm64 function not 4-byte aligned: _llint_program_prologue from /Users/rocky/DEV/EjectaGames/BesideYou/Source/lib/JavaScriptCore.framework/JavaScriptCore(LowLevelInterpreter.o)

**Comment by cmtoa** [comment]
Is their a fix for this yet I still cant seem to fix mine

**Comment by phoboslab** [comment]
I don't get any warnings with a fresh clone of the repository with XCode 6.1.1. I suspect some compiler/linker settings could cause this. Can you please check? Also, the exact warning messages would be helpful.
