### ISSUE TITLE
Rebuilding doesn't copy updated App/ folder

### ISSUE THREAD

**Issue by nornagon** [phoboslab/Ejecta#370]
Updating App/index.js and then pressing 'run' in Xcode doesn't copy the new index.js for me -- I have to clean and rebuild in order to get the updated files. Is this a problem with my Xcode setup or do others see this as well?

Some light googling suggests that a workaround for this is to have a shell-script build step that copies the resources over every build (perhaps rsync could be employed to avoid copying things that haven't changed?)

**Comment by phoboslab** [comment]
Seems to be fixed in recent XCode versions.
