### ISSUE TITLE
Multithreaded rendering

### ISSUE THREAD

**Issue by AshleyScirra** [phoboslab/Ejecta#375]
I've noticed Ejecta has a single threaded renderer. Calls to both the 2D and WebGL contexts result in synchronous OpenGL calls on the same thread.

If context calls simply save their parameters, push the call to a queue then return, then it can return to the JS thread more quickly. Main thread contention is reduced and there is more time to run JS code (very much important on iOS since there is no JIT support). Then a separate renderer thread runs the queue and actually executes it. The driver code in actual OpenGL calls, as well as calculations made in the 2D context calls, can happen in parallel to the JS execution. The iPhone 4S and newer have dual-core processors so can definitely benefit from this, since rendering work can happen on a separate core. Modern browsers like Chrome employ this strategy to maximise performance.

A couple of notes:

- the 2D context binding should not be totally dumb and just forward all calls blindly; it would still be prudent to eliminate redundant calls such as setting the same composite mode, global alpha, font etc. multiple times in a row. (Construct 2 does this very frequently since the plugin architecture makes the state unpredictable.) WebGL mode however can just forward everything that is passed to it.

- in my experience many platforms have some limitations on the threaded use of OpenGL contexts; it may need a special creation mode, or the context may need to be created on the renderer thread, or you may need special calls like Windows' wglMakeCurrent to explicitly indicate control of the context is switching to another thread. iOS probably has its own quirks with this.

I will of course look in to this myself, but all of the codebase, language and platform are unfamiliar to me.

**Comment by phoboslab** [comment]
Closing for lack of interest. I don't think there's that much to gain here anyway. For Ejecta, most of the work is done on the GPU.
