### ISSUE TITLE
Ejecta and babylon.js : Z-Buffer issue ?

### ISSUE THREAD

**Issue by demonixis** [phoboslab/Ejecta#381]
Hi there,
 
I'm working on the port of a webgl app using Babylon and Ejecta. It seem that i've a z-buffer issue but I don't know if the problem is from Babylon or from Ejecta. I made a video that you can watch here (https://www.youtube.com/watch?v=we4UkUnRvmQ&feature=youtu.be) which show you the problem.
 
I tested different configurations with camera projection (minZ and maxZ) but it hasn't solved my problem. Have you an idea ? In fact I don't know where to start to debug this issue.

I also patched Babylon.js with this code

var depthWriteMask = this._gl.getParameter(this._gl.DEPTH_WRITEMASK);

// Enable depth mask when clearing depth buffer.
if (!depthWriteMask)
    this._gl.depthMask(true);

this._gl.clearDepth(1.0);

// clear

// Reset buffer write state
if (!depthWriteMask) {
     this._gl.depthMask(false);
}

but it's not solving the issue, have you an idea about problem ?

I reported this issue on HTML5GameDev forums, you can follow the post here http://www.html5gamedevs.com/topic/5764-ejecta-and-babylon-z-buffer-issue/
 
Thanks for your answers ;)
 
Yann.

**Comment by phoboslab** [comment]
Did you figure this out? Maybe it's just the depth buffer precision? iOS only has 24bits for the depth buffer.

**Comment by phoboslab** [comment]
Closing for lack of info.
