### ISSUE TITLE
Remote Web Inspector (debugging)

### ISSUE THREAD

**Issue by Blechhirn** [phoboslab/Ejecta#395]
Hi

I grabbed phoboslab/JavaScriptCore and built it with ENABLE_REMOTE_INSPECTOR set to 1 (TRUE) and used it with Ejecta. After this exercise I am able to connect Web Inspector to both the ejecta app on my phone, as well as the simulator.

However, the inspector itself seems to be in a zombie state. No resources show up, pausing does not work nor can I execute any JS calls from the console window.

Any pointers to what I am missing would be fantastic.

Manu

PS: I evaluated a couple of WebGL for iOS approaches (including cocoon.js) and Ejecta really is the one that is the most promising! Keep up the great work.

**Comment by phoboslab** [comment]
See #211
