### ISSUE TITLE
[Request]  A resource-loading system

### ISSUE THREAD

**Issue by finscn** [phoboslab/Ejecta#431]
Create a resource-loading system , move and  refactor all  functions about loading file into it .

Then user could  extend the custom loader for  some  reasons  (e.g.  protecting resource ).

In #384 and  #385  , I've talked about it , But it may be not a good design.  I think a extendible resource-loading system is a better solution.

=============

In china ,   software piracy and 山寨(steal resource-files from one game , then create a new game)  are very serious .   So , the software-protecting is a very Important thing.

**Comment by phoboslab** [comment]
Closing for lack of interest.
