### ISSUE TITLE
getting following error when compiling in C++11

### ISSUE THREAD

**Issue by weepy** [phoboslab/Ejecta#446]
A few of the following :

/EJCanvasContext2D.h:90:8: Type 'float' cannot be narrowed to 'unsigned char' in initializer list

e.g. this line 		EJColorRGBA.rgb.r = (float)color.rgba.r * alpha,

**Comment by phoboslab** [comment]
Nobody else with this problem. I may add support for compiling with C++11 when there's more demand.
