### ISSUE TITLE
Knowing when a js file has finished loading

### ISSUE THREAD

**Issue by abinop** [phoboslab/Ejecta#458]
I need to know when a large js file has finished loading. I am adding the js file this way

```
var ej_controller:EJAppViewController =  EJAppViewController(scriptAtPath: "index.js") 
self.mainview.addSubview(self.ej_controller.view)
```
So ideally I would expect to use a delegate function when all assets have been loaded...

**Comment by abinop** [comment]
I am afraid this does not work. For example I logged a message just before the end of ```- (void)loadView {``` inside the ```EJAppViewController.m``` but the message logs much earlier than the page loads...

To try the latter method, what can I call from within Javascript and then catch from Swift?

I need to find a good way to display a loading screen for pages that take time to load, see also https://github.com/phoboslab/Ejecta/issues/461

**Comment by phoboslab** [comment]
Then I guess what you define as "page load" does something asynchronously!?

Have a look at http://impactjs.com/ejecta/extending-ejecta to see how you can define your own class and functions and expose it to JS.

**Comment by abinop** [comment]
OK I managed to extend ejecta and get back when Construct page has loaded, however I need to interact with a UIView that is on the main view controller from within the ```initWithContext``` function. How can I do that?

**Comment by phoboslab** [comment]
It's not possible to do this from within EJBinding's `initWithContext`. It's the very first step when creating the EJBinding object. It doesn't know about the "outside world" yet. There's another method, `createWithJSObject`, that gets called immediately afterwards and attaches the JavaScript object and the EJScriptView to this ObjC object.

Something like this should work:
```objc
- (void)createWithJSObject:(JSObjectRef)obj scriptView:(EJJavaScriptView *)view {
	[super createWithJSObject:obj scriptView:view];
	
	[scriptView.window.rootViewController doSomething];
}
```

You could also define an instance function (using `EJ_BIND_FUNCTION()`) for your new class and do your work there. This may be more extensible than directly doing everything when instantiating the class.

**Comment by abinop** [comment]
Seems to be working ok.Thank you @phoboslab !
