### ISSUE TITLE
Could you creare a donate button for Ejecta?

### ISSUE THREAD

**Issue by finscn** [phoboslab/Ejecta#459]
Ejecta is a greate project for me. 
Before I met it, I had just developed some stupit web mini-games. 
Ejecta brings me to a new world.
Thank you for your work.

It is holiday now，the 64bit Ejecta is the best gift for me. I do't know how to repay you.

Could you creare a donate button for Ejecta? 
I want to donate a little money to you.

You know I am a poor chinese guy with poor English，but there is nothing could stop my love.

Thank you and Best Regards.

**Comment by phoboslab** [comment]
Buy a license for Impact or donate one to a friend if you want: http://impactjs.com/buy-impact

I don't want to have a dedicated donate button, because accepting donations would put some more responsibility for me on this repo - which I don't want at the moment. I hope you understand.
