### ISSUE TITLE
[Feature] A function for Checking if the files exist

### ISSUE THREAD

**Issue by finscn** [phoboslab/Ejecta#460]
example:

```
 ejecta.isFileExist("xxxx.xxx") ; // return true or false
```

**Comment by phoboslab** [comment]
Can't you just open an AJAX request for this file? If it produces an error (I think it should!?), the file doesn't exist.

**Comment by finscn** [comment]
In my case , I want to do something like this :  
```
if (  ejecta.isFileExist("xxxx.xxx") ) {
     //  load  file  "xxxx.xxx"
}
```

 ejecta.isFileExist is a  synchronized method.
the code only runs in Native .

**Comment by finscn** [comment]
@phoboslab  , Could you see my question at <https://github.com/phoboslab/Ejecta/pull/487#issuecomment-95001252> ?
