### ISSUE TITLE
Black Screen after update :(

### ISSUE THREAD

**Issue by moto0000** [phoboslab/Ejecta#462]
When i update ( 95787899d0cc08d3f9ced8dcadebbb4052794637 ) Ejecta project, iOS emulator return black screen but audio and touchevents work fine :(

**Comment by phoboslab** [comment]
Error messages? Test case?

**Comment by moto0000** [comment]
I haven`t any errors, game work fine but under black cantainer :( it`s work fine with old AlphaTexture

**Comment by phoboslab** [comment]
So only the alpha texture shader doesn't work?

**Comment by moto0000** [comment]
I don`t know, becouse i cant`t see te game, but when i touch i hear audio so game work fine but i see only black screen

**Comment by phoboslab** [comment]
Start reducing your code until you have the smallest possible code that exhibits this problem.

Also read: http://www.catb.org/esr/faqs/smart-questions.html :)

**Comment by moto0000** [comment]
I my opinion problem is with Canvas Shaders becouse before this commit game work fine :)

Now when i lunch game i see black screen, but console return messages that game works fine. When i lunch with Ejecta before this commit game works fine.

**Comment by phoboslab** [comment]
I'm accepting that there may be a problem with the latest commit, I just don't have any idea _what_ the problem is.

To fix the problem I need to be able to reproduce it. If you don't tell me how to reproduce it, I can't fix it.

**Comment by moto0000** [comment]
For my game I use Pixi.js and console returns this:
```
objc[28446]: Class JSWTFMainThreadCaller is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/JavaScriptCore.framework/JavaScriptCore and /Users/Maciek/Library/Developer/CoreSimulator/Devices/75D0EAE5-ECB9-4744-A065-66E98DA0D7B6/data/Containers/Bundle/Application/29A498BB-2F94-4AD9-A4C7-5C18EB314E0E/Ejecta.app/Ejecta. One of the two will be used. Which one is undefined.
2015-01-07 20:23:36.804 Ejecta[28446:2258005] Creating Offscreen Canvas (2D): size: 375x667, retina: yes = 750x1334, msaa: no
2015-01-07 20:23:36.809 Ejecta[28446:2258005] Creating Offscreen Canvas (2D): size: 1x1, retina: yes = 2x2, msaa: no
2015-01-07 20:23:36.935 Ejecta[28446:2258005] Creating ScreenCanvas (2D): size: 375x667, style: 375x667, retina: yes = 750x1334, msaa: no
2015-01-07 20:23:36.936 Ejecta[28446:2258005] Creating ScreenCanvas (2D): size: 375x667, style: 375x667, retina: yes = 750x1334, msaa: no
2015-01-07 20:23:36.936 Ejecta[28446:2258005] Creating ScreenCanvas (2D): size: 640x667, style: 640x667, retina: yes = 1280x1334, msaa: no
2015-01-07 20:23:36.937 Ejecta[28446:2258005] Creating ScreenCanvas (2D): size: 640x1136, style: 640x1136, retina: yes = 1280x2272, msaa: no
2015-01-07 20:23:36.937 Ejecta[28446:2258005] Creating Offscreen Canvas (2D): size: 1x1, retina: yes = 2x2, msaa: no
2015-01-07 20:23:36.939 Ejecta[28446:2258005] Creating ScreenCanvas (2D): size: 640x1136, style: 640x1136, retina: yes = 1280x2272, msaa: no
2015-01-07 20:23:36.941 Ejecta[28446:2258005] Creating ScreenCanvas (2D): size: 640x1138, style: 640x1136, retina: yes = 1280x2272, msaa: no
2015-01-07 20:23:36.942 Ejecta[28446:2258005] Creating ScreenCanvas (2D): size: 640x1138, style: 640x1138, retina: yes = 1280x2276, msaa: no
2015-01-07 20:23:36.942 Ejecta[28446:2258005] Creating ScreenCanvas (2D): size: 640x1138, style: 375x1138, retina: yes = 750x2276, msaa: no
2015-01-07 20:23:36.942 Ejecta[28446:2258005] Creating ScreenCanvas (2D): size: 640x1138, style: 375x667, retina: yes = 750x1334, msaa: no
```

**Comment by phoboslab** [comment]
Looks ok to me. It's resizing the canvas more often than it needs to, but that shouldn't be a problem.

Again, I need to reproduce this bug to fix it. Maybe start from a fresh Pixi.js project and see if it works or rather when it stops working!?

**Comment by supercranky** [comment]
I also got a black screen when I updated. It was very weird as it only happened when using the 2d canvas, webgl canvas worked fine. Also, it only happened when running an arm64 build. 

I did some detective work comparing the previous working version with the new one. I got a clue when analyzing an opengl frame from both versions. In the latest version all draw calls were made but the framebuffer object was invalid.

I tracked it down to this call in EJCanvasContext2DScreen.m (the resizeToWidth function):
```
[glContext renderbufferStorage:GL_RENDERBUFFER fromDrawable:(CAEAGLLayer *)glview.layer];
```
It seems that this call is made before the glview is ready, I'm guessing it's a threading issue? 
Anyway, by dispatching the call to the main thread
```
dispatch_async(dispatch_get_main_queue(), ^{
    [glContext renderbufferStorage:GL_RENDERBUFFER fromDrawable:(CAEAGLLayer *)glview.layer];
});
```
I got it working again. Not at all sure this is the right way to fix it, or if this really is a threading issue (seems unlikely as it works when running in armv7 mode and obviously has worked before) but it seems to be working fine now. Maybe this could help you track down what's really going on?

**Comment by phoboslab** [comment]
Nice work! I think I've narrowed it down to the previous commit, specifically these lines:
https://github.com/phoboslab/Ejecta/commit/be1a4cd1d63a103834a438ee9e8b844ca63b0b89#diff-f68a35d1c56441e51f7040d7f8177b3aR212

This causes `resizeToWidth` to be called before the canvas has a valid framebuffer. The `create` method is called later to create the framebuffer in the given size - but there may be an edge case in which the `create` method is not called or can't do its work properly for some reason.

Can you comment out this line https://github.com/phoboslab/Ejecta/blob/master/Source/Ejecta/EJCanvas/EJBindingCanvas.m#L214 and see if it makes a difference? Better stil, provide a test case so I can have a look.

**Comment by supercranky** [comment]
Commenting it out did the trick! Great!

**Comment by MaartenWeber** [comment]
Hi, I was also having a the black screen issue and tried to comment out the given line. It worked in a way that I now see the game, but the scaling seems to be off. As in the game is at twice the scale.

**Comment by phoboslab** [comment]
I've changed the order of context creation and resizing with the above commit. This will under certain circumstances create the context twice (the first framebuffer is created and immediately discarded again), so it will be a few milliseconds slower. I'm not sure if it even fixes the issue. Please give it a shot.

Also, someone PLEASE give me test-case :) I won't share it - promised! dominic.szablewski@gmail.com

**Comment by supercranky** [comment]
This commit also fixes the black screen issue. I'll try and whip together a test case for you!

**Comment by supercranky** [comment]
I have emailed you a project currently showing a black screen when tested on the iPhone 6 simulator (and also on device).

**Comment by MaartenWeber** [comment]
The latest commit fixed the black screen issue for me, thanks!
