### ISSUE TITLE
magictouch.js and tuio to emulate multitouch in the simulator

### ISSUE THREAD

**Issue by jedahan** [phoboslab/Ejecta#464]
So, by using [magictouch.js](https://github.com/borismus/MagicTouch/) and [TongSeng](https://github.com/fajran/tongseng) I have been able to use the iOS simulator to test multitouch without needing a real device.

Is this the best way to do things if you don't have hardware on hand? I am totally new to iOS dev so theres a high likelihood I am doing things completely backwards.

Should I document this somewhere? If so, where? As an example app? Wiki article? Blog post?

Or ignore it because its too much of an edge case...

**Comment by apitaru** [comment]
Jonathan, your solution makes sense - it allows you flexibility to explore
gestures. For vanilla gestures, the iOS simulator has a few tricks up its
sleeve:
https://developer.apple.com/library/ios/documentation/IDEs/Conceptual/iOS_Simulator_Guide/InteractingwiththeiOSSimulator/InteractingwiththeiOSSimulator.html

Amit

**Comment by jedahan** [comment]
Ahh that is super helpful, closing
