### ISSUE TITLE
Changing launch image?

### ISSUE THREAD

**Issue by condolent** [phoboslab/Ejecta#465]
Some reason, the launch image is set to the ejecta logo all the damn time, ever since I updated ejecta to the latest version..

How do I change so I can use my custom launch image??

**Comment by phoboslab** [comment]
Ejecta uses a single Launch Screen XIB, instead of the dozens of Images that were required previously. Just edit the `Resources/LaunchScreen.xib` and you're good to go :)

**Comment by condolent** [comment]
Just changing the file with an text editor and changing file name & size will do it? Or what's up? xd

**Comment by phoboslab** [comment]
Open the file in XCode. It will launch the Interface Builder where you can move things around or change the image.

**Comment by condolent** [comment]
Not working. When I change anything on it, it just gives me 4 errors when I try to test the app, "Apple Mach-O Linker Error" is what appears 4 times

**Comment by condolent** [comment]
Here's my errors:
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_SKMutablePayment", referenced from:
      objc-class-ref in EJBindingIAPProduct.o
  "_OBJC_CLASS_$_SKPaymentQueue", referenced from:
      objc-class-ref in EJBindingIAPManager.o
      objc-class-ref in EJBindingIAPProduct.o
  "_OBJC_CLASS_$_SKProductsRequest", referenced from:
      objc-class-ref in EJBindingIAPManager.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by condolent** [comment]
solved, accidently disabled in-app-purchase in xcode.

**Comment by hermanbanken** [comment]
@condolent I just figured out that you do not need to enable In-App-Purchases to circumvent that issue. You can also just add StoreKit.framework in "Linked Frameworks and Libraries" instead. If your not actually doing IAP that is. For example GoogleMobileAds.framework requires this dependency, which does not necessarily means that you want to enable IAP.
