### ISSUE TITLE
[Issue] Display Loading screen (Construct 2 latest version related // Latest Ejecta version)

### ISSUE THREAD

**Issue by ThisMushroom** [phoboslab/Ejecta#469]
Im using the latest Ejecta version along with latest Construct 2 version.
Game runs just perfect but still I face the loading screen problem - it is not shown, only black screen instead.

From the xcode log I can see that loading screen resources are being loaded first and after that - Ejecta creates ScreenCanvas (WebGL).
But nothing is shown.

From little log snippets I also figure that my Loading layout is being loaded and had to be shown.

I ask you for some help managing this problem.

Thank you!

**Comment by phoboslab** [comment]
Dup: https://github.com/phoboslab/Ejecta/issues/461
I don't think there's much you can do about that. Maybe you can replace Construct 2's loader to not DOM elements!?
