### ISSUE TITLE
semantic issues

### ISSUE THREAD

**Issue by matrixreal** [phoboslab/Ejecta#470]
hi,
i use the latest ejecta from this sourceand i get this error
any help please ?

![sans titre](https://cloud.githubusercontent.com/assets/6823974/6320928/02e3b310-baec-11e4-9d9d-7b7a5c7d989a.png)

**Comment by matrixreal** [comment]
any help please ?

**Comment by phoboslab** [comment]
Update XCode. The current Version is 6.1.1 I believe.

**Comment by matrixreal** [comment]
6.3 is out !!! did any one try the new ejecta with xcode 6.3 ?
thanks
