### ISSUE TITLE
Admob and ios 8 (Ejecta)

### ISSUE THREAD

**Issue by Pasha187** [phoboslab/Ejecta#471]
I downloaded admob plugin for Construct2 How I can start the project in xcode with support of admob and ios 8?

**Comment by finscn** [comment]
My fork includes new admob extension and supports iOS 8. 
https://github.com/finscn/Ejecta

**Comment by Pasha187** [comment]
It doesn't work at the portrait mode. Gives out a mistake. How to work in the portrait mode?
