### ISSUE TITLE
Ejecta as React Native Component

### ISSUE THREAD

**Issue by francoislaberge** [phoboslab/Ejecta#472]
It would be rad if Ejecta ends up being wrapped as a Component for Facebook's React Native project.
http://facebook.github.io/react-native/

I just started playing around with it this morning, it is super slick.

**Comment by phoboslab** [comment]
Closing for lack of interest.

**Comment by francoislaberge** [comment]
Yeah, makes sense. After looking through the code it would be a lot of work and not really fit with the goals of the project anyway. Thanks!

**Comment by stoffern** [comment]
Too bad, looking at how big React Native is now.. :(

**Comment by brentvatne** [comment]
I agree this would be awesome :)

**Comment by stoffern** [comment]
There is already a good native Canvas library on the `gl-react-native` repo. Could it be possible to use this in combination with the Ejecta core?

**Comment by flyskywhy** [comment]
@francoislaberge , maybe you need [@flyskywhy/react-native-gcanvas](https://github.com/flyskywhy/react-native-gcanvas), it's very fast on Android, but slow on iOS, may someone integrated Ejecta by merge https://github.com/flyskywhy/react-native-gcanvas and https://github.com/DanielKoehler/react-native-canvas
