### ISSUE TITLE
Wrong Middle Baseline calculation?

### ISSUE THREAD

**Issue by Tharit** [phoboslab/Ejecta#473]
The offset for kEJTextBaselineMiddle is currently calculated as:
(ascender-descender)/2

I have some fonts were it is very obvious that something is wrong; but even for standard fonts like arial and helvetica, the offset is slightly different from the one used in the browser.

The documentation (http://www.w3.org/wiki/CSS/Properties/vertical-align) I've found states:

middle
Align the vertical midpoint of the box with the baseline of the parent box plus half the x-height of the parent

This would suggest
CTFontGetXHeight(ctMainFont)/2

I've done some tests, and for some of the fonts I have that produces much better results. For some others, I'm not quite sure however.. still seems to be different from what the browser does.

**Comment by phoboslab** [comment]
Thanks! The W3 spec makes it quite clear that `xHeight/2` is the right way to do this.

**Comment by JaryGuo** [comment]
but safari webkit and chrome webkit both use `(ascender-descender)/2`
