### ISSUE TITLE
ejecta and 64 bits architecture

### ISSUE THREAD

**Issue by matrixreal** [phoboslab/Ejecta#474]
hi all,
since apple force us to send ipa with standard architecture and 64 bits
i'm trying to convert ejecta project to standard architecure but get 55 erros and warnings
any help please ?
thanks

**Comment by phoboslab** [comment]
The current Ejecta version in this repository already supports arm64 and has the _Architectures_ set to `$(ARCHS_STANDARD)` (armv7, arm64). Which Ejecta version are you on.

**Comment by matrixreal** [comment]
i use this https://github.com/finscn/Ejecta
i need it becuse it contains admob

**Comment by finscn** [comment]
@matrixreal , I will update my fork of Ejecta after #398 be fixed.(it's very important to me) .
 Please wait.

**Comment by matrixreal** [comment]
@finscn 
its okay i will wait till you update your forked ejecta because i need admob
but tel me have any solution to add chartboost plugin ?

@phoboslab 
its ok but is it optimized for ?

thanks in advance

**Comment by finscn** [comment]
@matrixreal  , I don't know anything about chartboost , but I think it's not difficult.

**Comment by matrixreal** [comment]
do you have skype or anything else i have some elements can help us to make chatboost plugin
thanks

**Comment by finscn** [comment]
@matrixreal  ,  my fork has updated. 
Now It includes new Google Admob.     
Please try (and test)  it.   Thanks.

**Comment by matrixreal** [comment]
@finscn 
can you include new chartboost sdk ?
thanks a lot

**Comment by finscn** [comment]
@matrixreal , I've added Chartboost.framework .
 But I'm no time to code the Extension of Chartboost.

**Comment by matrixreal** [comment]
thanks a lot 
all is working fine except for chartboost when i try to do what is written in this guide
https://answers.chartboost.com/hc/en-us/articles/201220095-iOS-Integration
i got that errors and warnings
![error](https://cloud.githubusercontent.com/assets/6823974/7107456/6730162e-e166-11e4-8242-b789c81985f6.png)
