### ISSUE TITLE
warning xcode 6.2 with lastest ejecta

### ISSUE THREAD

**Issue by matrixreal** [phoboslab/Ejecta#476]
hi,
i just update my xcode to 6.2 the project is build success but i have some warning
can anyone tel us what is about and maybe how to remove them ?
thanks a lot 

![warning](https://cloud.githubusercontent.com/assets/6823974/7083832/c1b9bae8-df66-11e4-90d2-b4c494ae0bc2.png)

**Comment by matrixreal** [comment]
any help please ?

**Comment by phoboslab** [comment]
You can ignore these warnings for now. "Deprecated" just means that these properties will be removed in a future iOS SDK Version.

Does anybody know if there's an alternative for the `isFriend` property.

**Comment by finscn** [comment]
I think @matrixreal  use my fork .   GameCenter of my fork has more features , but some methods used  old APIs ( because I need   compatible to iOS 6 )

**Comment by matrixreal** [comment]
yes i use fok of finscn

**Comment by finscn** [comment]
@matrixreal  , yes,  you are right. 
I think I have to rebuild   EJBindingGameCenter , because new iOS supports some new APIs of GameCenter.

It's a complex task, I will do it later.

**Comment by phoboslab** [comment]
If it's an issue with @finscn's fork, please discuss this in his repo.
