### ISSUE TITLE
any futur project for apple watch export ?

### ISSUE THREAD

**Issue by matrixreal** [phoboslab/Ejecta#482]
hi,
it seem that apple will release these days the "Apple Watch"
i would like to know if its possible to export for apple watch ?
thanks

**Comment by finscn** [comment]
I think it's impossible.  Because Apple Watch doesn't support OpenGL ES...

**Comment by phoboslab** [comment]
As far as I know, there's no SDK to run an App directly on the Watch yet. Current Apple Watch Apps run on your iPhone and only send a View over to the watch for displaying.

Maybe it's possible to render an Ejecta View on the iPhone and stream Video to the Watch, but this would be a huge hack.
