### ISSUE TITLE
About   consts for true & false

### ISSUE THREAD

**Issue by finscn** [phoboslab/Ejecta#488]
I see  many methods  used   
```
JSValueMakeBoolean(scriptView.jsGlobalContext, true) 
//or  
JSValueMakeBoolean(scriptView.jsGlobalContext, false)
```

Should we create consts for true & false   (like  jsUndefined )?

**Comment by finscn** [comment]
in #353 , @phoboslab  , you tell me jsUndefined was added for performance reasons.
in this issue,  I want to add jsTrue & jsFalse are for  "short code" :)

**Comment by phoboslab** [comment]
`jsUndefined` is the default return value of `EJ_BIND_FUNCTION` when the function itself does not return a JSValue. This was done to speed up performance critical canvas functions that may be called hundreds of times per frame. The speedup is minimal, though.

Most functions that return `true` or `false` are not performance critical.
