### ISSUE TITLE
the best default value of  "retinaResolutionEnabled" is false, I think

### ISSUE THREAD

**Issue by finscn** [phoboslab/Ejecta#489]
I use Ejecta developed many games ( for demo/test/game jam ..., not on App Store ), I've never used  retinaResolutionEnabled = true.

In all of my use cases ,   canvas.width/height & canvas.style.width/height could solve all problems about canvas's resolution.

---------------------------------
But I have to  set retinaResolutionEnabled = false every time.

I don't know  why the value of  retinaResolutionEnabled=true .

----------------------------------

Update:

I found that  screen-canvas need  retinaResolutionEnabled=true .
But in common , offscreen-canvas doesn't .

**Comment by finscn** [comment]
in https://github.com/phoboslab/Ejecta/issues/274#issuecomment-31588856 , 
@phoboslab 's code tell us a truth :  
RetinaI Device need "retinaResolutionEnabled = false" ,  
only  non-RetinaI Device need "retinaResolutionEnabled = true" .

Now , Most of the device are RetinaI ,   so I think retinaResolutionEnabled's default value should be false

**Comment by matrixreal** [comment]
i use ejecta for my games on appstore
and i thin for iphone 4 i think that i need to set retina resolution to = true
or maybe there is some thing to autodetect this feature

**Comment by finscn** [comment]
@marixreal , 
canvas.width=w*window.devicePixelRatio
canvas.style.width=w

set height like above

**Comment by matrixreal** [comment]
@finscn where i put this code ?

**Comment by finscn** [comment]
anywhere after you create screencanvas

**Comment by matrixreal** [comment]
you mean by any where on index.js ?

**Comment by finscn** [comment]
@matrixreal , yes.  when you've created the screencanvas, you can change width/height and style.width/height anytime

**Comment by matrixreal** [comment]
i put your code like that in index.js 
           canvas.width = w * window.devicePixelRatio;
           canvas.height = h * window.devicePixelRatio;
           canvas.style.width = w ;
           canvas.style.height = h;
i got this error 

2015-04-21 22:03:43.938 Ejecta[908:60b] SyntaxError: Unexpected end of script at line 25027 in index.js

**Comment by finscn** [comment]
the w/h means a variable you used.  In my case  w/h= window.innerWIdth/innerHeight

**Comment by matrixreal** [comment]
ok then i just need to add
var w = window.innerWIdth
var h = window.innerHeight
correct ?

**Comment by finscn** [comment]
yes.    window.innerWidth

**Comment by finscn** [comment]
I found that  screen-canvas needs  retinaResolutionEnabled=true .
But in common , offscreen-canvas doesn't .

**Comment by matrixreal** [comment]
@finscn 
when i use  useRetinaResolution = false; i have bad quality image so i use set to true

**Comment by phoboslab** [comment]
The `useRetinaResolution` property has been removed. See https://github.com/phoboslab/Ejecta/issues/555
