### ISSUE TITLE
Lexical or preprocessor issue 'unordered_map' file not found when compiling

### ISSUE THREAD

**Issue by AlexBezuska** [phoboslab/Ejecta#490]
Hey I'm not exactly sure what I can do to fix this, any help is appreciated! 
XCode 6.1.1
Ejecta 1fd028381bc620383e31d6a152cdd509c178c3e8

**Comment by finscn** [comment]
in Old iOS   , please use : 
#include <tr1/unordered_map>

in New iOS ( 7.0+) , please use:
#include <unordered_map>

Doesn't  the Ejecta  support iOS 6.x  ,   @phoboslab  ?

**Comment by finscn** [comment]
now , I create a PR for solving  this problem  see #494

**Comment by phoboslab** [comment]
Sorry, no. iOS6 is no longer supported. Apple currently lists iOS < 7.0 with only %2 market share: https://developer.apple.com/support/appstore/

**Comment by AlexBezuska** [comment]
Good point, I did not think of that! When I build for target iOS 7 it works fine :)
