### ISSUE TITLE
About App Icon and LaunchScreen 

### ISSUE THREAD

**Issue by finscn** [phoboslab/Ejecta#493]
the lastest iOS Human Interface Guidelines  are changed: https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/IconMatrix.html

the Ejecta missed  icon-60@3x.png  and some launch screen images

=============
update:

in  https://developer.apple.com/library/ios/qa/qa1686/_index.html

 I see Ejecta  just  supports the Required icon .

But  the launch screen in iOS 6.x , must be static png image .

**Comment by phoboslab** [comment]
iOS6 is no longer supported. Using a `LaunchScreen.xib` made things a lot easier and I don't want to go back to providing PNGs in dozens of different sizes.
