### ISSUE TITLE
[BUG] no target on Touch Object

### ISSUE THREAD

**Issue by finscn** [phoboslab/Ejecta#498]
see
http://www.w3.org/TR/touch-events/#touch-interface
and
http://www.w3.org/TR/touch-events/#touchevent-interface

the Touch is different from Mouse. 
the  target attribute is not on TouchEvent , it's on  Touch.
But in Ejecta , it's on TouchEvent.

I think it's a bug.

**Comment by phoboslab** [comment]
Ejecta provides a sensible, minimal _subset_ of the DOM APIs. Use the TouchEvent's `target`. As you said yourself, it's always `window.canvas` anyway.

**Comment by finscn** [comment]
But  most  gesture-lib get touch's `target` from  `touchObject.target`.

**Comment by phoboslab** [comment]
Fine :)
