### ISSUE TITLE
performance ? 

### ISSUE THREAD

**Issue by matrixreal** [phoboslab/Ejecta#504]
@phoboslab 
you say that for performance we have to put in index.js this code :

// In your game class; Overwrite load level do enable 
// pre-rendering on all background maps when a level 
// was loaded

loadLevel: function( data ) {
    this.parent( data );
    
    for( var i = 0; i < this.backgroundMaps.length; i++ ) {
        this.backgroundMaps[i].preRender = true;
    }
}
t
hat give me an error ... can you give us an example please ?

because i have this error 

2015-04-22 14:13:54.110 Swing Copters[734:6269] SyntaxError: Function statements must have a name. at line 23825 in index.js

thanks

**Comment by phoboslab** [comment]
Are you sure these lines are causing the error? The error message looks like the problem might be somewhere else. Hard to say without source.

**Comment by matrixreal** [comment]
yes i have a lot of big background between 120x120 to 500x500 ...
i just add these lines on the end of my main js "index.js" and i get this error and game stuck on black screen
if i delete your lines there is no error and the game is lunch normally

**Comment by phoboslab** [comment]
Well, this doesn't sound like a good case for pre-rendering then. What's line 23825 in your index.js?

**Comment by matrixreal** [comment]
the 23825 line is simply 
loadLevel: function( data ) {this.parent( data );

**Comment by matrixreal** [comment]
@phoboslab 
is this mean that the prerender not work or maybe i do something wrong ?
maybe be i put it in wrong area (index.js)

**Comment by phoboslab** [comment]
Pre-Rendering generally works; Ejecta shouldn't have any problems with it.

You're probably missing a curly brace somewhere. Show some code.

**Comment by matrixreal** [comment]
@phoboslab 
BUT if i delete the lines (for prerendering) code work good and there is no error
you sure that i can put these lines in index.js ?

**Comment by phoboslab** [comment]
Oh. No you can't put these lines in your `index.js` just like this! It should be a property of your Game Class.

```
// In your GAME CLASS; Overwrite loadLevel do enable 
// pre-rendering on all background maps when a level 
// was loaded
```

```
MyGame = ig.Game.extend({

	// ... your game stuff...

	loadLevel: function( data ) {
		this.parent( data );

		for( var i = 0; i < this.backgroundMaps.length; i++ ) {
			this.backgroundMaps[i].preRender = true;
		}
	}

	// more game stuff
});
```

**Comment by matrixreal** [comment]
whats game class ?
i only have index.js , media (for sound) and images folder ...

**Comment by amadeus** [comment]
Wait, @matrixreal - are you using ImpactJS?

**Comment by matrixreal** [comment]
@amadeus 
no i'm using construct 2 and export to ejecta
it generate an index.js and media and image folder

**Comment by amadeus** [comment]
The code that @phoboslab suggested is for ImpactJS only
