### ISSUE TITLE
Loading Sound(OpenAL) always twice ???

### ISSUE THREAD

**Issue by matrixreal** [phoboslab/Ejecta#505]
@phoboslab 
hi i'm using contruct 2 to developp a game
1- and i call action trigger once to play audio but i'm always get loading sound(OpenAl) twice like the picture attached ?
2- alternative : is there a way to preload / load sound on start of ejecta like loading the images ?
thanks a lot
![audio](https://cloud.githubusercontent.com/assets/6823974/7287164/70202bf4-e952-11e4-9064-d75c33a8f8d2.png)

**Comment by phoboslab** [comment]
I don't know much about Construct2, sorry.

**Comment by matrixreal** [comment]
@phoboslab ok is there a way in ejecta to load all sound on start like images ?

**Comment by phoboslab** [comment]
If the audio element's `.preload` property is not `"none"`, the file will be loaded as soon as the path is set. You can also explicity call `.load()`

```javascript
var audio = new Audio();
audio.preload = 'auto';
audio.src = 'some-file.m4a';

// or
audio.load();
```

**Comment by matrixreal** [comment]
so i have to load manually file by file at the start of index.js , right ?

**Comment by phoboslab** [comment]
To achieve what?

**Comment by matrixreal** [comment]
to preload sound for example i have 3 sound to load
so i put this code 
var audio = new Audio();
audio.preload = 'auto';
audio.src = 'file1.m4a';
audio.src = 'file2.m4a';
audio.src = 'file3.m4a';
yes ?

**Comment by matrixreal** [comment]
not work

**Comment by phoboslab** [comment]
Well, you throw the loaded sounds away after loading, so that's not surprising.

If you need further help, my hourly rate is $150.

**Comment by amadeus** [comment]
That will not work. Each time you set the src, a file will start to load. In this snippet  you are overwriting the src 3 times. The only file that will eventually load is file3.

**Comment by matrixreal** [comment]
@phoboslab ok no problem how can i mail you ?
@amadeus anyway thanks

**Comment by phoboslab** [comment]
Cool. You can reach me at dominic.szablewski@gmail.com

**Comment by matrixreal** [comment]
@phoboslab check your mail

**Comment by matrixreal** [comment]
i'm waiting for your reply

Date: Thu, 23 Apr 2015 12:51:42 -0700
