### ISSUE TITLE
Unable to rename the "Ejecta" project in Xcode

### ISSUE THREAD

**Issue by ertdfgcvb** [phoboslab/Ejecta#512]
When renaming the project Xcode crashes immediately and the Ejecta.xcodeproj will be corrupted.
Tested on version Xcode 6.3.1

**Comment by phoboslab** [comment]
Bug in XCode. See http://stackoverflow.com/questions/29824737/xcode-6-3-1-crashes-while-renaming-project

**Comment by ertdfgcvb** [comment]
Oh well! Thanks for pointing it out…!

**Comment by 7php** [comment]
Hello this is a known bug with xcode 6.3.1 
A word of caution: renaming manually here and there is simply a risk and time-consuming.

Two Solutions exist:

1- Upgrade to Xcode 6.3.2 GM seed or later

2- Replace by command-line - it’s fast & furious..urm effective!! *Mention not*

### Install Ack. For info on Ack, see: http://beyondgrep.com/why-ack/
    $ brew install rename ack


### Two Commands to execute to do renaming - one for File names & 2nd for 'leterals' inside files

    $ find . -name 'OldProjectName*' -print0 | xargs -0 rename -S 'OldProjectName' 'NewProjectName'

    $ ack --literal --files-with-matches 'OldProjectName' | xargs sed -i '' 's/OldProjectName/NewProjectName/g'


### /Check to see if all renaming was a success. The following command indicates a success if no result is output
    $ ack --literal 'OldProjectName'
