### ISSUE TITLE
webRTC ???

### ISSUE THREAD

**Issue by matrixreal** [phoboslab/Ejecta#513]
hi,
is there a way to implement WebRTC
a lot of game engine like construct 2 use it for multiplayer 
thanks

**Comment by phoboslab** [comment]
Way outside the scope of Ejecta. WebRTC is a huge API and supporting it would be a tremendous endeavour.

You can use WebSockets for realtime multiplayer stuff.

**Comment by matrixreal** [comment]
@phoboslab 
thanks for reply
but i read that the websockets not allow the browser to browser or client to client communication
here http://stackoverflow.com/questions/4118272/do-websockets-allow-for-p2p-browser-to-browser-communication
and here http://stackoverflow.com/questions/4277351/can-html5-websockets-connect-2-clients-browsers-directly-without-using-a-serve
so ?
