### ISSUE TITLE
crash when perform In-App Purchase ???

### ISSUE THREAD

**Issue by matrixreal** [phoboslab/Ejecta#514]
@phoboslab 
some times when i try to buy some thing (iap) the game is crashing with the following warning like the picture attached 
can you take a look please ?
and apple reject the app because of crashing and bugs when iap is performing
![v](https://cloud.githubusercontent.com/assets/6823974/7557617/38344350-f795-11e4-8964-2bc35aa4b1dc.png)

**Comment by phoboslab** [comment]
This seems to happen when the IAP Transaction fails, but there's no Error object. See http://stackoverflow.com/questions/15426056/skpaymenttransactionstatefailed-but-no-nserror

The above commit should fix this.
