### ISSUE TITLE
Couldn't find JSTypedArray.h?

### ISSUE THREAD

**Issue by condolent** [phoboslab/Ejecta#517]
Not sure but when I tried to run my app in xcode, it gave me an error that the file EJBindingHttpRequest.m couldn't find JSTypedArray.h for some reason when I try importing it with
`#import <JavaScriptCore/JSTypedArray.h>`

Anyone know why?

**Comment by condolent** [comment]
I've checked and the file is there.

**Comment by condolent** [comment]
Noticed now that no file can import JSTypedArray.h because 'it's not found'... What is wrong?! IT'S THERE!

**Comment by phoboslab** [comment]
Try re-downloading this repo. Some project setting has probably gone missing (Framework Search Path).
