### ISSUE TITLE
Ejecta 1.5 does not build on OSX 10.10.3 (latest) with Xcode 6.3.2 (latest)

### ISSUE THREAD

**Issue by Joncom** [phoboslab/Ejecta#518]
Build fails with latest OSX and Xcode. 
However, older OSX (10.9.3) and Xcode (5.1.1) work fine. 
See screenshots below:

![Screenshot](http://i.imgur.com/x3xPhZC.png)

![Screenshot](http://i.imgur.com/RKhSKku.png)

**Comment by phoboslab** [comment]
Works fine for me on 6.3.2. Are you using the latest Ejecta version from this repo? Maybe you're trying to compile for an older architecture?

**Comment by Joncom** [comment]
Ah, that's it. Latest in master builds no problem. 1.5 however, will not build, as in screenshot. I wonder if maybe a new release is due, or perhaps a note in the README?

**Comment by Joncom** [comment]
I've updated the title to more accurately describe this issue.
