### ISSUE TITLE
restore iap problem

### ISSUE THREAD

**Issue by matrixreal** [phoboslab/Ejecta#519]
@phoboslab 
i see that the restore iap is performed automatically in the ejecta lunch
and it always ask for user and password 
is there a way to delete the restore iap on lunch of ejecta and make sure that the restore action is only called when the user want it
thanks a lot

**Comment by phoboslab** [comment]
Ejecta's IAP doesn't attempt to restore purchases on launch. You have to explicitly call `.restoreTransaction` for this. See http://impactjs.com/ejecta/in-app-purchases#restoretransactions

My guess is, that the login prompt comes from GameCenter. See the documentation for `.authenticate` and `.softAuthenticate`: http://impactjs.com/ejecta/game-center
