### ISSUE TITLE
memory warning cear cache ?

### ISSUE THREAD

**Issue by matrixreal** [phoboslab/Ejecta#520]
@phoboslab
i have sometimes memory warning (because i'm using revmob to display video)
i would like to know how to call automatic clear cache when the memory warning 
thanks

**Comment by matrixreal** [comment]
@phoboslab 
i know that maybe you are busy but i'm trying to done it since 2 days ago with no success
i hate cocoonjs and phonegab also cordova
i like ejecta and i will never change it for other :D

**Comment by matrixreal** [comment]
any one knows how to do it?

**Comment by phoboslab** [comment]
Ejecta will release some cached textures and also trigger a JavaScript garbage collection when it receives a memory warning.

There's not much else that can be cleared. I have no idea what revmob does or how/when it releases memory.

**Comment by matrixreal** [comment]
@phoboslab 
i'm using this method and files to add revmob ads
https://gist.github.com/neogope/5574438

but if i keep these lines in appdelegate.m

app = [[EJApp alloc] initWithWindow:window];
        
    [self.window makeKeyAndVisible];
    return YES;
}
 
- (void)applicationWillResignActive:(UIApplication *)application {
    [app pause];
}
 
- (void)applicationDidEnterBackground:(UIApplication *)application {
    [app pause];
}

- (void)applicationWillEnterForeground:(UIApplication *)application {
    [app resume];
}
 
- (void)revmobAdDidFailWithError:(UIApplication *)application {
    [app resume];
}

- (void)applicationDidBecomeActive:(UIApplication *)application {
    [app resume];
}
 
- (void)applicationWillTerminate:(UIApplication *)application {
    [app pause];
}

#pragma mark -
#pragma mark Memory management
 
- (void)applicationDidReceiveMemoryWarning:(UIApplication *)application {
    [app clearCaches];
}
 
- (void)dealloc {
    [app release];
    [super dealloc];
}
@end
i got error build this error
error "app = [[EJAppViewController alloc] initWithWindow:window]; use of undeclared identifier app"

if i delete these lines every thing works good except after shwing 5 or 6 ads i got warning memory in the debug and after some seconds the app crach

**Comment by matrixreal** [comment]
is there a way to clear a cache once the memory warning is display?

**Comment by matrixreal** [comment]
any update please ?

**Comment by phoboslab** [comment]
https://developer.apple.com/library/ios/recipes/Instruments_help_articles/FindingMemoryLeaksinYourApp/FindingMemoryLeaksinYourApp.html
