### ISSUE TITLE
Wrong character is displayed via XMLHttpRequest load.

### ISSUE THREAD

**Issue by homma-ge** [phoboslab/Ejecta#523]
Hi. I have a trouble about XMLHttpRequest on Ejecta. 

The below code works well on Google Chrome/Mac but does not work well on Ejecta/iPhone.

test.json
```
{
	"text": "ʃ"
}
```

sample.js
```
var request = new XMLHttpRequest();
request.open( 'GET', 'test.json', true );
request.addEventListener( 'load', function ( event ) {
	var json = JSON.parse(this.response);
	console.log(json.text);    // "ʃ" should be indicated.
}, false );
request.send( null );
```

On Google Chrome, "ʃ" is correctly indicated as "ʃ" on console, but on Ejecta, "ʃ" is indicated as "Ê".

By the way, just 
```
console.log("ʃ") 
```
is correctly displayed as "ʃ" on Ejecta.

Does anyone know why this issue occurs?

Thanks

**Comment by phoboslab** [comment]
Ejecta assumes the response charset is ASCII if none is given. Just add a charset header (probably utf-8) server side.

**Comment by homma-ge** [comment]
Thank you for your comment.
I think so, too. But 'test.json' is local file on iPhone, not on server side. In the case, how do I change charset header to utf-8?

**Comment by homma-ge** [comment]
BindingHttpRequest.m
```
- (NSString *)getResponseText {
	...
	NSStringEncoding encoding = NSASCIIStringEncoding;
	...
```
The above NSASCIIStringEncoding seems to affect this issue.

**Comment by phoboslab** [comment]
You're right. For local files Ejecta should assume utf8 encoding. The above commit should fix your issue.
