### ISSUE TITLE
Warning about loading JS Core

### ISSUE THREAD

**Issue by thepian** [phoboslab/Ejecta#526]
I'm a newbie with Ejecta. I see this warning with the latest master. Is there a way to get rid of it? 

Do I have a bad project configration?

objc[25807]: Class JSWTFMainThreadCaller is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/JavaScriptCore.framework/JavaScriptCore and /Users/henrikvendelbo/Library/Developer/CoreSimulator/Devices/8389C038-EFEA-4C7B-911B-2708B1915594/data/Containers/Bundle/Application/1E5EAD2F-7425-43D2-9D43-A0D404EBA55F/Today.app/Today. One of the two will be used. Which one is undefined.

**Comment by finscn** [comment]
same to #479  .
