### ISSUE TITLE
On fillText() of Canvas, Simplified Chinese and Korean font is not indicated correctly.

### ISSUE THREAD

**Issue by homma-ge** [phoboslab/Ejecta#528]
Japanese, Portuguese and Spanish font is displayed correctly, but Simplified Chinese and Korean is not. 

Would you confirm it?

**Comment by phoboslab** [comment]
You have to set a font that contains characters for these languages.

```javascript
ctx.font = '16px AppleGothic';
ctx.fillText('한국어', 100, 100);
```
