### ISSUE TITLE
Uploading blobs via XHR?

### ISSUE THREAD

**Issue by presstube** [phoboslab/Ejecta#531]
Hi there,

I'm trying to upload an image (a blob to S3) from an Ejecta app I'm building.

I see this [closed issue](https://github.com/phoboslab/Ejecta/issues/31) saying that blob uploads will likely not be supported.

A couple of years have passed, has there been any movement on this front, or is it still impossible to upload an image via Ejecta?

Many thanks,

**Comment by phoboslab** [comment]
We still don't have support for Blobs (they're stupid anyway ._.), but we do have ArrayBuffers. With the above commit, you can send raw binary data now.

```javascript
var request = new XMLHttpRequest();

request.open('POST', 'http://example.com');
request.send( new Uint8Array([66,76,69,72]) );
```

**Comment by presstube** [comment]
Wow, super speedy response, weeee!

Thanks very much : )

ps. And in general thanks for all the great work with Ejecta.
