### ISSUE TITLE
xhr.getAllResponseHeaders() doesn't seem to be working

### ISSUE THREAD

**Issue by presstube** [phoboslab/Ejecta#533]
Ahoy!

In the 'Supported APIs' page it looks like `xhr.getAllResponseHeaders()` is supported, and I see your bindings for it [here](https://github.com/phoboslab/Ejecta/blob/master/Source/Ejecta/EJUtils/EJBindingHttpRequest.m#L186-L198).

But whenever I call `xhr.getAllResponseHeaders()` in action it doesn't seem to be working. It returns `undefined`.

Are you seeing the same thing?

All the best & thanks in advance!

**Comment by phoboslab** [comment]
<img width="888" alt="screen shot 2015-07-31 at 23 54 48" src="https://cloud.githubusercontent.com/assets/443987/9018491/a0d3bd48-37df-11e5-9f36-9f7a54ca8557.png">
Works for me™

Maybe you're trying to call this function when the xhr hasn't finished yet, or you're trying to get headers for a local file request?

**Comment by presstube** [comment]
Thanks a lot for getting back to me so quickly.

Yes, I am indeed trying to load a local file, good tip.
It revealed what's actually happening.

When a browser loads a local file `xhr.getAllResponseHeaders()`  returns an empty String, whereas in Ejecta it returns `NULL` from obj-c, which is `undefined` by the time it gets back to JS.

This breaks code which is expecting the browser-like empty String behaviour.

In my case I'm trying to use the [fetch](https://github.com/github/fetch) polyfill w/ Ejecta.
fetch runs `xhr.getAllResponseHeaders().trim().split('\n')` on all requests.
That's ok in the browser when it's expecting a string, but chokes when running in Ejecta as `undefined.trim()` leads to a TypeError.

Would you be open to returning an empty String rather than NULL [here](https://github.com/phoboslab/Ejecta/blob/master/Source/Ejecta/EJUtils/EJBindingHttpRequest.m#L188) to bring Ejecta closer to match the browser's implementation?

Just in case I've submitted a PR.

Cheers!

**Comment by phoboslab** [comment]
[According to MDN](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest#getAllResponseHeaders()) getAllResponseHeaders() should return `null` (well, we still return `undefined`) when there's no response yet. However, if there is a response but we have no headers, this function returns an empty string now. This should fix your problem, I believe.

Thanks!

**Comment by presstube** [comment]
Fantastic, thanks Dominic!

Much appreciated

**Comment by ryansix** [comment]
wwfwf
