### ISSUE TITLE
large console.log()'s inside the animation loop can brick an iOS device

### ISSUE THREAD

**Issue by sleepygarden** [phoboslab/Ejecta#534]
I came across this when debugging a Three.js project.` console.log(<something pretty large>)` inside of the `requestAnimationFrame(animate)` loop can completely brick a device for about half an hour. I'm testing on an iPad and it's Home and Lock buttons become completely unresponsive, or are partially responsive (ex: double tap home to quit an app opens, but can not redraw the device screen after a quit). Reading the device logs after I recover the device indicates that `debugserver` has crashed and it seems like a lot of daemons are shutting down user interaction. It's not intentional, but I keep stumbling across this issue while debugging (logging object3D instead of object3D.name, etc). After about half an hour, it seems that iOS kills my app with signal 9 (too much memory consumed) and I can resume using the device.

```js
var camera,scene,renderer;
function init() {
    var WIDTH = canvas.width;
    var HEIGHT = canvas.height;
    
    scene = new THREE.Scene();
    renderer = new THREE.WebGLRenderer({
        antialias: true,
        canvas: document.getElementById('canvas')
    });
    renderer.setSize(WIDTH, HEIGHT);

    camera = new THREE.PerspectiveCamera(45, WIDTH / HEIGHT, 1, 2000);
    scene.add(camera);
}
function animate() {
    requestAnimationFrame(animate);
    // log an entire Object3D's vertices, a large array of Vector3's, something large
    render();
}

function render(){
    renderer.render(scene,camera);
}

init();
animate();
render();

```

If / When I encounter it again I'll be sure to get the system logs right before after it becomes bricked. In the meanwhile, I'm building a log replacement that debounces console.log, and if too many attempts are made in a small amount of time, I hook into my iOS binding and call `exit(1)` from my Obj-C

**Comment by sleepygarden** [comment]
Here is my workaround. iOS is my custom .LogPanicLimit and LogPanicDelay


```objc
//  EJBindingLogPanic.h
#import "EJBindingBase.h"

// if you try and console.log PANIC_LIMIT # of times without resting 
// for at least PANIC_DELAY millis, iOS will exit(1)
#define JSLOG_PANIC_LIMIT 1000
#define JSLOG_PANIC_DELAY 100

@interface EJBindingLogPanic : EJBindingBase
@end

//  EJBindingLogPanic.m
#import "EJBindingLogPanic.h"

@implementation EJBindingLogPanic
EJ_BIND_CONST(Limit, JSLOG_PANIC_LIMIT);
EJ_BIND_CONST(Delay, JSLOG_PANIC_DELAY);
EJ_BIND_FUNCTION(Raise, ctx, argc, argv) {
    NSLog(@"[Fatal Error!]: JS LOG did panic, attempts %i logs without a %i ms break",
               JSLOG_PANIC_LIMIT,
               JSLOG_PANIC_DELAY);
    exit(1);
    return NULL;
}
@end


```

```js

activateLogPanicWatch();
function activateLogPanicWatch() {
    var logFunc = console.log;
    var logsRequested = 0;
    var timeout;
    function clearLogCount() {
        logsRequested = 0;
    }
    function chokedLog(){
        logsRequested++;
        if (logsRequested > LogPanic.Limit){
            LogPanic.Raise();
        }
        else {
            logFunc.apply(this,arguments);
            clearTimeout(timeout);
            setTimeout(clearTimeout, LogPanic.Delay);
        }
    }
    console.log = chokedLog;
}
````

**Comment by phoboslab** [comment]
Am I right to assume the conversion to a logable string (i.e. `JSON.stringify()`) is the culprit here? If so, I'd rather kill the stringify conversion at maybe 2 levels deep, but I'm not sure if this is plausible. I think we'd need to the conversion in ObjC, rather in JS.

Earlier implementations of the log methods didn't stringify at all - which is not the _right_ way either, imho. Maybe we can just cut of the string at a certain length somehow? Or pre-process the object in JS - i.e. just copy the top 2 layers of the object into a new one before calling `JSON.stringify()` on it?

**Comment by sleepygarden** [comment]
I think the issue is that it takes longer to print out the large log than it does to reach the next log request in the animation loop; ie: if it takes 20ms to log an array of vertices, and your frame rate is faster than 20ms per frame. This builds up a queue of log writes which is constantly growing. I suspect that those iOS log writes are dispatched to a separate process (debugserver?) because even a system exit of the app's process will continue to spit out logs (but it will stop growing that queue). Moreover, I can continue to interact with the App just fine (albeit with a laggy framerate). But once I try to background the app or quit the app from xcode / the device, everything goes haywire. It's possibly just because it's a debug environment, but that console write queue seems highly privileged inside of iOS, so everything important in iOS else starts to fail, like touch or LCD daemons. I think once that console write queue has finally flushed it's contents, then the rest of the system can get time to act.
