### ISSUE TITLE
Missing Push Notification Entitlement 

### ISSUE THREAD

**Issue by williammalone** [phoboslab/Ejecta#539]
After distributing my app using Ejecta to the App Store I receive this message:

Missing Push Notification Entitlement - Your app appears to include API used to register with the Apple Push Notification service, but the app signature's entitlements do not include the "aps-environment" entitlement. If your app uses the Apple Push Notification service, make sure your App ID is enabled for Push Notification in the Provisioning Portal, and resubmit after signing your app with a Distribution provisioning profile that includes the "aps-environment" entitlement. See "Provisioning and Development" in the Local and Push Notification Programming Guide for more information. If your app does not use the Apple Push Notification service, no action is required. You may remove the API from future submissions to stop this warning. If you use a third-party framework, you may need to contact the developer for information on removing the API.

I am not using push notifications and cannot find where the API is referenced in Ejecta or elsewhere to remove it.  Has anyone run into this issue before?

**Comment by matrixreal** [comment]
i think its related to your certificate and not ejecta

**Comment by williammalone** [comment]
Thanks matrixreal. I was unable to remove the warning with the changes to my certificate, still not sure what is causing it.  However my app was approved today so the warning didn't affect getting approved. Closing issue.
