### ISSUE TITLE
SocketRocket has updated many times, May Ejecta should merge something.

### ISSUE THREAD

**Issue by finscn** [phoboslab/Ejecta#541]
I don't know what's SocketRocket changed , But It seems better than old version. 

https://github.com/square/SocketRocket/commits/master

**Comment by matrixreal** [comment]
@finscn 
is this for websocket ?

**Comment by finscn** [comment]
@matrixreal  yes

**Comment by phoboslab** [comment]
Fixed in https://github.com/phoboslab/Ejecta/commit/5be70b3f646012a9b6b80d553414584994ef4901
