### ISSUE TITLE
Build Issues in Xcode 7: Conflicting Return Type

### ISSUE THREAD

**Issue by williammalone** [phoboslab/Ejecta#544]
Two issues appear when trying to build in Xcode 7 (Beta) and Xcode 7 (GM Seed). I do not get these errors when building in previous versions of Xcode.  The errors are very similar:

1. Conflicting return type in implementation of 'supportedInterfaceOrientations': 'UIInterfaceOrientationMask' (aka 'enum UIInterfaceOrientationMask') vs 'NSUInteger' (aka 'unsigned int')

2. Conflicting return type in implementation of 'supportedInterfaceOrientations': 'UIInterfaceOrientationMask' (aka 'enum UIInterfaceOrientationMask') vs 'NSUInteger' (aka 'unsigned long')

![screen shot 2015-09-11 at 12 42 40 pm](https://cloud.githubusercontent.com/assets/391204/9823475/b15919c8-5883-11e5-9e32-32757908a973.png)

Is anyone else experiencing this?  Any advice on how to fix these issues would be much appreciated!

**Comment by finscn** [comment]
this could help you : 
https://forums.developer.apple.com/thread/6165

**Comment by williammalone** [comment]
Hi finscn. Thank very much for the link! I am a little nervous making changes to the framework, but given the time restraints I'll give it a try.

**Comment by williammalone** [comment]
I have made the changes described in the correct answer on the thread provided.  It seems to have worked.  Thanks again finscn!
