### ISSUE TITLE
@phoboslab , would you like  to create a MetalEjecta ?

### ISSUE THREAD

**Issue by finscn** [phoboslab/Ejecta#548]
I found a project named MetalGL  , it uses  Metal to implement  openGL API  ( https://metalgl.com ).
Would you like to create a MetalEjecta  with  Metal to implement  HTML5 Canvas ?

**Comment by phoboslab** [comment]
Well, it's not free, so I don't think it makes sense to base Ejecta on it. I'm also quite wary of their performance claims.

I think it would be a better idea to implement Canvas directly in Metal (or maybe wait for Vulcan on iOS!?) than to use a tool like this.

**Comment by amadeus** [comment]
What is this Vulcan for iOS that you speak of?
