### ISSUE TITLE
CanvasRenderingContext2D can't handle globalAlpha if it's a string

### ISSUE THREAD

**Issue by jmo84** [phoboslab/Ejecta#550]
The context's globalAlpha property was inadvertently being set with a string in my app's code. On Chrome for Mac OS X it worked fine, but in Ejecta all draw calls with the string globalAlpha value fail. I'm using a work around for now; I check if the alpha value is a string and use parseFloat during the loading phase of my app. The official specification says that globalAlpha must not be NaN, and a string value of "0.5" is counted as a number in JavaScript. 

So to match the specification, you should accept numeric strings in the setter for globalAlpha. 

Reference: https://html.spec.whatwg.org/multipage/scripting.html#dom-context-2d-globalalpha

**Comment by phoboslab** [comment]
This was conscious decision for performance reasons. None of Ejecta's API functions that take Numbers as arguments will convert Strings automatically. So `fillRect()` for example will fail in the same way. 

Imho, there's no good reason to handle Float values as Strings. Fix your code :)

Also see https://github.com/phoboslab/Ejecta/blob/master/Source/Ejecta/EJConvert.m#L22

**Comment by jmo84** [comment]
My code was never broken according to the W3C. I had to introduce a work-around especially for Ejecta in my application because a third party gave me strings instead of floats. I don't think it's wise to ignore the specification for performance reasons - especially when a defect is causing a silent failure that's hard to trace. If it didn't work in a normal browser I would take the blame, but it works in all browsers except Ejecta. I don't care if this never gets fixed and from your reply it sounds like it won't. I only opened this issue so nobody else has to pull their hair out over this anomaly.

**Comment by phoboslab** [comment]
Lot's of things that work in Browsers don't work in Ejecta. Ejecta aims to support a sensible subset of features. If it would support everything a Browser does, it would be as slow as a Browser.

You do have a point about silently failing. Maybe we could log a warning message in `JSValueToNumberFast` when it encounters anything else than a Number value.
