### ISSUE TITLE
Dose Ejecta still support iOS 7.x ?

### ISSUE THREAD

**Issue by finscn** [phoboslab/Ejecta#551]
Today , @phoboslab updates many things (Thank you @phoboslab ) .
Could you tell me Dose Ejecta still support iOS 7.x ?
I don't have iOS 7 device and    iOS 7 simulator , but I know many iOS devices are under iOS 7.x .

Thank you very much .

**Comment by matrixreal** [comment]
@finscn 
hi
update your fork to lastest ejecta here and don't forget to fix webgl take screenshoot and i will test it on ios7 here
thanks
