### ISSUE TITLE
What is "Ejecta copy-Info" doing for ?

### ISSUE THREAD

**Issue by finscn** [phoboslab/Ejecta#552]
How to use "Ejecta copy-Info.plist" file?

**Comment by phoboslab** [comment]
That's part of the tvOS build. The name was still the default after copying the scheme. I have renamed the file now (https://github.com/phoboslab/Ejecta/commit/ddd8782f609f44044acf669a0d56a6b050d93b2f). It's the default plist file for the new Ejecta-TV scheme.
