### ISSUE TITLE
There is no "texture" in EJCanvasContextWebGLScreen

### ISSUE THREAD

**Issue by finscn** [phoboslab/Ejecta#553]
So  I can't draw WebGL-screen-canvas on another canvas

**Comment by phoboslab** [comment]
Getting pixel data from the screen canvas is pretty slow. Canvas2D supports this, but it's much better to use an offscreen Canvas if you need it frequently.

For WebGL you have a bunch of other options, too, when you want to draw to textures.

What's the use case here? Your screen is displaying a WebGL Canvas and you want to use it in an offscreen Canvas2D? Why? There's probably a better, faster way.

**Comment by finscn** [comment]
It's about   taking a screenshot.  I want  create a UIImage from screen-canvas

**Comment by phoboslab** [comment]
I don't have a test case. Can you try this?
```objc
// At the top of EJCanvasContextWebGLScreen.m
#import "EJJavaScriptView.h"

// Somewhere further down...
- (EJTexture *)texture {
	EJCanvasContext *previousContext = scriptView.currentRenderingContext;
	scriptView.currentRenderingContext = self;

	NSMutableData *pixels = [NSMutableData dataWithLength:bufferWidth * bufferHeight * 4 * sizeof(GLubyte)];
	glReadPixels(0, 0, bufferWidth, bufferWidth, GL_RGBA, GL_UNSIGNED_BYTE, pixels.mutableBytes);
	
	EJTexture *texture = [[[EJTexture alloc] initWithWidth:bufferWidth height:bufferHeight pixels:pixels] autorelease];
	texture.contentScale = backingStoreRatio;

	scriptView.currentRenderingContext = previousContext;
	return texture;
}
```


Note that for the purpose of making Screenshots (i.e. getting an `UIImage` from the _screen canvas_), the `.texture` methods are quite slow (and possibly inaccurate!?):
1) pixel data from the canvas is read using `glReadPixels`
2) a texture is created from this pixel data
3) the texture is drawn into an offscreen buffer
4) pixel data is read from that buffer using `glReadPixels()`
5) a `UIImage` is created from the pixel data

Notice how we could skip step 1-3 :/

**Comment by finscn** [comment]
I test  https://github.com/finscn/Ejecta/blob/d3ee5c3605cfcae6f77961688109792da0644719/Source/Ejecta/EJCanvas/WebGL/EJCanvasContextWebGLScreen.m#L118  

that's ok.
Thank you.

**Comment by finscn** [comment]
The texture in  EJCanvasContextWebGLTexture is also slow  ?

**Comment by phoboslab** [comment]
Yep. Same way as in EJCanvasContext2DScreen. Pixels -> Texture -> Pixels -> UIImage.

It's obviously faster to create the UIImage directly from the pixel data. Something like this:
```objc

- (UIImage *)image {
	EJCanvasContext *previousContext = scriptView.currentRenderingContext;
	scriptView.currentRenderingContext = self;

	NSMutableData *pixels = [NSMutableData dataWithLength:bufferWidth * bufferHeight * 4 * sizeof(GLubyte)];
	glReadPixels(0, 0, bufferWidth, bufferWidth, GL_RGBA, GL_UNSIGNED_BYTE, pixels.mutableBytes);
	
	UIImage *image = [EJTexture imageWithPixels:pixels width:bufferWidth height:bufferHeight scale:backingStoreRatio];

	scriptView.currentRenderingContext = previousContext;
	return image;
}
```
