### ISSUE TITLE
[SUGGEST]Use asset for app icons

### ISSUE THREAD

**Issue by finscn** [phoboslab/Ejecta#558]
like picture:

<img width="483" alt="2015-10-20 8 28 18" src="https://cloud.githubusercontent.com/assets/288367/10607014/32c9ab5e-7769-11e5-9be6-44838e4eed63.png">

<img width="194" alt="2015-10-20 8 28 23" src="https://cloud.githubusercontent.com/assets/288367/10607012/312fe1a0-7769-11e5-9992-e9b5da6e1140.png">

**Comment by phoboslab** [comment]
Fixed in https://github.com/phoboslab/Ejecta/commit/0731e4214cf758077465a95c6b92a52bbf632b09

**Comment by finscn** [comment]
miss   Icon-60@3x.png   in AppIcon
