### ISSUE TITLE
[BUG] Updated Ejecta (#146a028) malloc fails in getActiveAttrib

### ISSUE THREAD

**Issue by sleepygarden** [phoboslab/Ejecta#560]
after updating, any call to render() will fail and spit this out

    EjectaDemo(419,0x40081000) malloc: *** mach_vm_map(size=1074270208) failed (error code=3)
    *** error: can't allocate region
    *** set a breakpoint in malloc_error_break to debug

breakpointing shows this coming from `getActiveAttrib` inside `EJBindingCanvasContextWebGL.m`

    EJ_BIND_FUNCTION(getActiveAttrib, ctx, argc, argv) {
    	if( argc < 2 ) { return NULL; }
    	
    	scriptView.currentRenderingContext = renderingContext;
    	
    	GLuint program = [EJBindingWebGLProgram indexFromJSValue:argv[0]];
    	GLuint index = JSValueToNumberFast(ctx, argv[1]);
    	
    	GLint buffsize;
    	glGetProgramiv(program, GL_ACTIVE_ATTRIBUTE_MAX_LENGTH, &buffsize);
    	
    	GLchar *namebuffer = malloc(buffsize);
    	GLsizei length;
    	GLint size;
    	GLenum type;
    	glGetActiveAttrib(program, index, buffsize, &length, &size, &type, namebuffer);
    	
    	NSString *name = @(namebuffer); // <-- Right Here
    	free(namebuffer);
    	
    	return [EJBindingWebGLActiveInfo createJSObjectWithContext:ctx
    		scriptView:scriptView size:size type:type name:name];
    }

I'm suspicious of creating a `NSString*` using `@(GLUint*)`, the shorthand for `NSNumber* creation`, and there's been some recent activity on this file. I suspect from the error code that we're running out of memory, maybe the new TypedArray support isn't properly releasing objects?

**Comment by phoboslab** [comment]
Well, I don't see anything inherently wrong with the `getActiveAttrib` function. But as you said, it's quite possible that we have a memory leak somewhere with the Typed Array stuff now. I'll have a closer look.

**Comment by phoboslab** [comment]
I checked some of my own WebGL stuff again and didn't notice any problems.

Can you please check if this error occurs at this version as well: https://github.com/phoboslab/Ejecta/commit/d4ee589d9eebd3cd1d920d0d544ac5c20dd6aefd - the commit after this one introduced a new version of the JSC library.

**Comment by sleepygarden** [comment]
I can run my App fine on the master branch of Ejecta, and there aren't many differences between my iOS app implementation and yours. Of note, my EJJavaScriptView isn't the root view of my view controller, so it isn't full screen. This happens

    Creating ScreenCanvas (WebGL): size: 824x600, style: 400x600
    Creating ScreenCanvas (WebGL): size: 824x768, style: 400x600
    Creating ScreenCanvas (WebGL): size: 824x768, style: 824x600
    Creating ScreenCanvas (WebGL): size: 824x768, style: 824x768

right before my `render()` call which fails. I'm still stepping through my iOS code to pin the issue down.

**Comment by sleepygarden** [comment]
This might be a linking problem - I can run 100% of my code inside of Ejecta master, including my EJJavaScriptView subview. Very odd.

**Comment by phoboslab** [comment]
Closing for now. Let me know if you find anything!
