### ISSUE TITLE
Issue creating/using custom extension

### ISSUE THREAD

**Issue by activetheory** [phoboslab/Ejecta#563]
Hi,

Thanks for this awesome project.

I'm trying to create a class using the instructions for [Extending Ejecta](http://impactjs.com/ejecta/extending-ejecta), copying the exact h and m code for EJBindingSimpleTest.

However, in JavaScript, Ejecta.SimpleTest is undefined. Interestingly, when I try to use some other extension built into Ejecta, such as Ejecta.ImagePicker, that is also undefined.

I've added the code to a top-level group called Extension
![screen shot 2015-11-01 at 10 17 01 pm](https://cloud.githubusercontent.com/assets/1118248/10875345/4e5ba094-80e6-11e5-9614-e0aaa8499d02.png)

I feel like I may be missing something very simple here, but I tried searching and couldn't find anything to help.

Thanks!

**Comment by phoboslab** [comment]
Make sure your `EJBindingSimpleTest.m` is compiled for the current target: Project -> Targets -> Build Phases -> Compile Sources. XCode asks you to which targets you want to add a new file.

If you compile for tvOS, the `Ejecta.ImagePicker` is disabled, because tvOS has no image picker.

**Comment by activetheory** [comment]
Amazing, I knew it was something silly. Thank you!
