### ISSUE TITLE
[BUG] fillText / strokeText  doesn't  support  Chinese

### ISSUE THREAD

**Issue by finscn** [phoboslab/Ejecta#564]
the old version supported , new version  doesn't  support.
The js file is already encoded with utf-8.
console.log is correct.
```
var testText="你好123";
console.log(testText)
context.fillText(testText,100,100);
```

**Comment by phoboslab** [comment]
Which version worked?

**Comment by finscn** [comment]
the last version on the github.      displayed messy code 
<img width="141" alt="2015-11-03 11 28 41" src="https://cloud.githubusercontent.com/assets/288367/10912038/a0a4999e-8282-11e5-9b76-a7f04736b2e2.png">

you could try it ,   "你好" in Chinese means "Hi , Hello"
:

**Comment by finscn** [comment]
@phoboslab  , thank you.    
There are many differences between   iOS font-system  and Web font-system , So sad , tears :'(

**Comment by finscn** [comment]
HTML5 supports  multi font name ,  If one font doesn't contain characters for one language, the browser will try another font.

**Comment by phoboslab** [comment]
You said it worked in an old version. Which one?

There may be a bug in the font rendering. The code should actually fallback to an international font if a glyph is not available in the current one. I.e. if attempt to draw Chinese characters with Helvetica, it should automatically fall back to AppleGothic for these characters, but still draw everything else with Helvetica.

**Comment by finscn** [comment]
"You said it worked in an old version. Which one?"  :  I found because in that version I set fontName  "STHeitiSC-Medium" , So it doesn't worked

**Comment by phoboslab** [comment]
Meh. This bug was introduced in https://github.com/phoboslab/Ejecta/commit/11ed432829ce06e50db43f0908297a418d743a0a -  `CGContextShowGlyphsAtPoint` has been deprecated and I used `CTFontDrawGlyphs` with the wrong font.

Thanks.
