### ISSUE TITLE
How to get a function form a json object

### ISSUE THREAD

**Issue by finscn** [phoboslab/Ejecta#566]
in js:
```javascript
ejecta.foo({
 a: 1,
 b: 2,
 callback: function(){ }
});
```
foo is a  binding function , how to get  function "callback"  in OC ?

**Comment by phoboslab** [comment]
Use JSC's [JSObjectGetProperty](https://developer.apple.com/library/mac/documentation/JavaScriptCore/Reference/JSObjectRef_header_reference/index.html#//apple_ref/c/func/JSObjectGetProperty).

You may also want to have a look at Ejecta's [jsValueForPath](https://github.com/phoboslab/Ejecta/blob/master/Source/Ejecta/EJJavaScriptView.m#L338), but it always uses the global object as root.
