### ISSUE TITLE
[Request] A method to reload the game

### ISSUE THREAD

**Issue by finscn** [phoboslab/Ejecta#568]
just like 
window.location.reload()  in browser.

Reset  everything in js context and  ObjectiveC context.

Thanks.

**Comment by finscn** [comment]
I see #310  .  but  ejecta.load('index.js') is not enough .
Some objects created in Native Context can't be reset .

I hope there is a method to recreate  scriptView and jsGlobalContext .

**Comment by finscn** [comment]
Sorry , I make a mistake.    ``` load```  could   recreate scriptView and jsGlobalContext  with loadViewControllerWithScriptAtPath

**Comment by phoboslab** [comment]
Yes, `ejecta.load()` should reset everything.

**Comment by finscn** [comment]
@phoboslab  ,

I hope   there could be a variable  for saving current index script file's path , then  Ejecta could supply a
 method like  "reload" : 
```
ejecta.reload();
window.location.reload();
```

In the case,  developers don't care of what's name of index script  when they want to reload.

**Comment by finscn** [comment]
@phoboslab  ,  you could see : 

https://github.com/finscn/Ejecta/commit/9b684ee1b58b445573c5a827f40278d716c34a8f

There are too many differences between  my  fork version and yours , So I don't give a PR , sorry

**Comment by phoboslab** [comment]
Well, the stock AppDelegate in Ejecta always loads `index.js`. So you could write a reload function like this:
```javascript
window.location.reload = function() {
    ejecta.load('index.js');
};
```
