### ISSUE TITLE
Apple tv

### ISSUE THREAD

**Issue by Piggies** [phoboslab/Ejecta#569]
I tried to archive my application to itunes connect with Ejecta-TV.
I'm getting this warning texts: 

<img width="874" alt="3tv" src="https://cloud.githubusercontent.com/assets/9120150/11164363/29a84ed0-8af7-11e5-8d3c-fd11281cdfb3.png">

What am i missing?

**Comment by Piggies** [comment]
solved

**Comment by phoboslab** [comment]
How? Which files exactly were needed? [The Docs](https://developer.apple.com/tvos/human-interface-guidelines/icons-and-images/) suggest we need a layered icon and top shelf image?!

**Comment by phoboslab** [comment]
Should be fixed with https://github.com/phoboslab/Ejecta/commit/0731e4214cf758077465a95c6b92a52bbf632b09
