### ISSUE TITLE
A small audio with loop =true , it can NOT  be play after loaded.

### ISSUE THREAD

**Issue by finscn** [phoboslab/Ejecta#572]
A small audio with loop =true , it can NOT be play after loaded.
If set loop=false  or  force use EJAudioSourceAVAudio (change the source of ejecta) , everything will be ok.

**Comment by phoboslab** [comment]
Can you upload the audio file, please?

**Comment by finscn** [comment]
This issue disappeared , I don't know why . Maybe I make something wrong.
