### ISSUE TITLE
black screen with webgl

### ISSUE THREAD

**Issue by matrixreal** [phoboslab/Ejecta#573]
Hi,
i'm contruct 2 users .... now with the latest update of ejecta i got black screen ... game is lunch but always black screen (since you add antialias and preserveDrawingBuffer system)
thanks for help

**Comment by phoboslab** [comment]
So is does it work without antialias?

**Comment by matrixreal** [comment]
i don't know will try to ask 
however here is a part of the main index.js wich contain the word antialias when webgl is enabled
it set to false , i try to set it true but nothing change
[index.txt](https://github.com/phoboslab/Ejecta/files/46148/index.txt)

**Comment by phoboslab** [comment]
Look at the log when the App starts. You should see something like this:
`Creating ScreenCanvas (2D): size: 640x1136 320x568 antialias:no, preserveDrawingBuffer: no`

The last occurrence of this line is the important one.

**Comment by matrixreal** [comment]
don't find what you ask

there are only 

if (this.enableWebGL && (this.isCocoonJs || this.isEjecta || !this.isDomFree))
			{
				attribs = {
					"alpha": alpha_canvas,
					"depth": false,
					"antialias": false,
					"failIfMajorPerformanceCaveat": true
				};
				this.gl = (this.canvas.getContext("webgl", attribs) || this.canvas.getContext("experimental-webgl", attribs));
			}
		}

and 

			this.ctx = this.canvas.getContext("2d", attribs);
				}
				this.ctx["webkitImageSmoothingEnabled"] = this.linearSampling;
				this.ctx["mozImageSmoothingEnabled"] = this.linearSampling;
				this.ctx["msImageSmoothingEnabled"] = this.linearSampling;
				this.ctx["imageSmoothingEnabled"] = this.linearSampling;
			}
			this.overlay_canvas = null;
			this.overlay_ctx = null;
		}
		this.tickFunc = function (timestamp) { self.tick(false, timestamp); };
		if (window != window.top && !this.isDomFree && !this.isWinJS && !this.isWindowsPhone8)
		{
			document.addEventListener("mousedown", function () {
				window.focus();
			}, true);
			document.addEventListener("touchstart", function () {
				window.focus();
			}, true);

**Comment by phoboslab** [comment]
So, antialias is probably not the problem. Need more info.

https://www.google.com/search?q=how+to+report+bugs

**Comment by matrixreal** [comment]
bugs reported and it is fixed in r218
it was c2 bug (full scaling to high quality)
thanks a lot
