### ISSUE TITLE
[BUG] About XmlHTTPRequest , call "send" once , server got  3 requests

### ISSUE THREAD

**Issue by finscn** [phoboslab/Ejecta#574]
Call XmlHTTPRequest.send  once , server got 3 requests.

Clien code: 
```
var url="http://mytestserver/something"
var xhr = new XMLHttpRequest();
xhr.open("GET", url, true);
xhr.send(null);
```

Server code is very simple (use node.js + express)
```
"use strict";

var port = process.argv[2] || 8088;

var util = require("util");
var express = require('express'),
    http = require('http');


var app = express();

app.get("/*", function(req, res) {
    console.log("====================");
    console.log("req.headers", req.headers);
    console.log("req.url", req.url);
    res.end("ok")
});


var httpServer = http.createServer(app);
httpServer.listen(port, function() {
    console.log("HTTP Server listening on " + port);

});
```

I found the key of this bug is  :   method=="GET"  and send a data
There is a bug when use: 
```
xhr.send(anything);
```

No bug : 
xhr.send();

**Comment by finscn** [comment]
Another bug:
server responses "ok" , but  in callback   client's  xhr.respoonseText is a  empty object , console.log display"

```
JS LOG: {}
```

**Comment by finscn** [comment]
Another bug:
server responses "ok" , but  in callback   client's  xhr.responseText is a  empty object , console.log display:
```
JS LOG: {}
```

**Comment by finscn** [comment]
All test cases  run correct in browser

**Comment by phoboslab** [comment]
Which callback? It seems to work fine for me. Note though that `null` will log as an empty object. I'll fix that:

```javascript
var url="http://localhost:8088/something"
var xhr = new XMLHttpRequest();
	
xhr.onreadystatechange = function() {
	console.log('state', xhr.readyState, 'text', xhr.responseText);
};

xhr.open("GET", url, true);
xhr.send();
```

```
JS LOG: state: 3 text: {}
JS LOG: state: 2 text: ok
JS LOG: state: 4 text: ok
```

Also, `xhr.send(null);` will send the string `"null"` as HTTP body data. The [spec](https://xhr.spec.whatwg.org/#dom-xmlhttprequest-send) actually says to ignore body data for GET or HEAD requests :/
