### ISSUE TITLE
The official JavaScriptCore.framework can coexist with Ejecta ?

### ISSUE THREAD

**Issue by finscn** [phoboslab/Ejecta#578]
Some 3rd tools need  The official JavaScriptCore.framework (build in iOS 7+ ), 
Can it  coexist with Ejecta ?

**Comment by phoboslab** [comment]
Would be difficult to set up, I think. You'd have to make sure each of sources links to the right JSC framework.

Try this Ejecta branch - it uses the JSC framework provided by the OS: https://github.com/phoboslab/Ejecta/tree/typed-array-clusterfuck

**Comment by finscn** [comment]
I can't checkout  typed-array-clusterfuck branch , Why  ?

**Comment by phoboslab** [comment]
What did you do? What did you expect to happen? What happened instead? Did you see any error messages? 

https://www.google.de/search?q=how+to+report+bugs

`git clone -b typed-array-clusterfuck https://github.com/phoboslab/Ejecta.git` works for me.

**Comment by finscn** [comment]
I use:
```
git fetch
git branch -a
```
There is no ```typed-array-clusterfuck``` in the list

**Comment by phoboslab** [comment]
I think for older git versions you have to explicitly track the remote branch. See http://stackoverflow.com/questions/9537392/git-fetch-remote-branch

**Comment by finscn** [comment]
I found that thread, but no effect for me.
I have to clone the whole project again , now that's ok.

When could we used the Ejecta with JSC framework provided by the OS ?
 I very much look forward.

**Comment by matrixreal** [comment]
hope will new javascriptcore will be integrated soon as we need it to add new feature
anyway thanks for the info

**Comment by phoboslab** [comment]
Since the main branch of Ejecta now uses the system provided JSC lib, this issue is obsolete.
