### ISSUE TITLE
My new Ejecta Game is already on App Store

### ISSUE THREAD

**Issue by finscn** [phoboslab/Ejecta#580]
It's free and welcome to play it, Thanks

https://itunes.apple.com/app/fat-fall/id1054336310?mt=8

more detail at :  http://forums.toucharcade.com/showthread.php?t=277234

**Comment by rungo73** [comment]
Looks great!

Please look at mine.. Also free and also made with Ejecta.

https://geo.itunes.apple.com/au/app/devils-doom-endless-arcade/id977532235?mt=8

**Comment by finscn** [comment]
@rungo73  , your game is very great , it's better than mine . 
Could you introduce  how many downloaded  ?  thanks

**Comment by phoboslab** [comment]
Hey, very cool games!

I'd like to collect all Games/Apps made with Ejecta in a single thread: https://github.com/phoboslab/Ejecta/issues/581 

I will close this thread (#580) in a few days, but #581 will stay open for a long time.
