### ISSUE TITLE
About    "contentScale "

### ISSUE THREAD

**Issue by finscn** [phoboslab/Ejecta#585]
I think 
```
    float contentScaleX = bufferWidth / frame.size.width;
    float contentScaleY = bufferHeight / frame.size.height;
    float contentScale = contentScaleX > contentScaleY ? contentScaleX : contentScaleY;
```
is better than  just using   ```bufferWidth / frame.size.width;```

This will ensure that request size always  <= Actual size

**Comment by phoboslab** [comment]
That's certainly the better approach to this problem. Thank you!
