### ISSUE TITLE
About Gamepad event 

### ISSUE THREAD

**Issue by finscn** [phoboslab/Ejecta#587]
in HTML5 , there are 2 events  "gamepadconnected"  "gamepaddisconnected".
I think we need them in Ejecta too.

UPDATE: I found Ejecta has them , but not fired ...

**Comment by finscn** [comment]
And I found  this HTML5 gamepad tester hard to run in Ejecta 

http://www.html5rocks.com/en/tutorials/doodles/gamepad/gamepad-tester/tester.html
(Ignore Render Method, please.  I know this tester uses DOM)

I hope Ejecta gamepad function could be compatible with HTML5

**Comment by phoboslab** [comment]
> I found sometimes user has to press one button to active the gamepad .(will fire "gamepadconnected")

I don't think there's anything we could do about this. Ejecta [directly forwards](https://github.com/phoboslab/Ejecta/blob/master/Source/Ejecta/EJUtils/Gamepad/EJBindingGamepadProvider.m#L25-L27) the `GCControllerDidConnectNotification` from iOS.

Btw., Browsers seem to do this as well:
> Even if you connect the gamepad, it won't manifest itself in any way unless the user presses any of its buttons first. 

~ http://www.html5rocks.com/en/tutorials/doodles/gamepad/
