### ISSUE TITLE
WebGLImageFilter instance not reusable.

### ISSUE THREAD

**Issue by udipl** [phoboslab/Ejecta#588]
Ejecta 2.0.0, renders a single instance of [WebGLImageFilter](https://github.com/phoboslab/WebGLImageFilter) not reusable.
The attached code, adapted from the [WebGLImageFilter demo web page](http://phoboslab.org/log/2013/11/fast-image-filters-with-webgl), does not work in Ejecta unless each new filter preset selection (via tap) is applied to a newly created WebGLImageFilter instance. Calling `filter.reset()`, as the HTML demo does, is not sufficient.

I attaching the [zipped index.js file that demonstrates this problem](https://github.com/phoboslab/Ejecta/files/70252/EjectaWebGLImageFilter.index.js.zip).

Tapping on the screen applies the first preset, but subsequent taps have no effect.
Moving the ` var filter = getFilter()` line into the touch event handler resolves the problem.

**Comment by phoboslab** [comment]
Should be fixed with https://github.com/phoboslab/Ejecta/commit/cb50b8ff50593533247ff0f499968431b5ea026f

Thanks for the test case!

**Comment by udipl** [comment]
Thanks!
