### ISSUE TITLE
Why are there some  red filenames ?

### ISSUE THREAD

**Issue by finscn** [phoboslab/Ejecta#594]
Like title says.

<img width="268" alt="2015-12-25 4 51 17" src="https://cloud.githubusercontent.com/assets/288367/12001651/96b5a09a-ab27-11e5-9242-0be74a8f34c6.png">

**Comment by phoboslab** [comment]
The JavaScriptCore.framework was still referenced by accident. The above commit removes it.

Ejecta-TV.app is not present if you never build the project for the Apple TV. Not sure what's going on with Info-TV.plist. It works for me in a freshly cloned version of Ejecta.
