### ISSUE TITLE
Is new Ejecta slower than old Ejecta (with custom JSC) ?

### ISSUE THREAD

**Issue by finscn** [phoboslab/Ejecta#597]
Is new Ejecta slower than old Ejecta (with custom JSC) ?

I see new Ejecta use EJConvertTypedArray for  TypedArray,   Is it  as fast as  old Ejecta ?

**Comment by phoboslab** [comment]
The new `EJConvertTypedArray` is significantly slower than it was in old versions. In old versions Typed Array data access was instant (constant time), while in the current version all bytes have to be copied. However, with the new version, we don't need the custom JSC anymore, which makes your App smaller.

The current way to access Typed Array data is only a workaround until [this webkit bug](https://bugs.webkit.org/show_bug.cgi?id=120112) is fixed - so only 1 or 2 more years :/

**Comment by finscn** [comment]
Thanks . maybe I have to use  your  JSC lib still. My game use many  getImageData putImageData
