### ISSUE TITLE
FaceBook ads is in conflict with Ejecta.

### ISSUE THREAD

**Issue by finscn** [phoboslab/Ejecta#599]
<img width="464" alt="2015-12-28 5 46 42" src="https://cloud.githubusercontent.com/assets/288367/12020581/e1a23ca6-adb8-11e5-8824-a766e6c295fb.png">

It looks about JSC.
I don't know what can I do . Could you give me some suggestions ,@phoboslab .
Thanks.

**Comment by benji011** [comment]
Hi,
How can I reproduce this issue?
Can you tell me what you did to get this error? 

Thanks

**Comment by phoboslab** [comment]
This should be fixed now that Ejecta is using the JSC lib provided by the system. Can you confirm, please?

**Comment by finscn** [comment]
If use system JSC , everything is ok .
