### ISSUE TITLE
ctx.clip() doesn't allow multiple paths

### ISSUE THREAD

**Issue by jamesnvc** [phoboslab/Ejecta#60]
According the spec:

>The clip() method must create a new clipping region by calculating the intersection of the current clipping region and the area described by the intended path, using the non-zero winding number rule. 

However, Ejecta's implementation only clips to the most recent clipping path.

**Comment by phoboslab** [comment]
Wontfix for lack of interest and because there are simple workarounds. I believe solving this would be quite complicated and memory intensive.
