### ISSUE TITLE
Is there no local storage in Apple TV ?

### ISSUE THREAD

**Issue by finscn** [phoboslab/Ejecta#601]
http://ericasadun.com/2015/09/09/developing-for-apple-tv-first-thoughts/

@phoboslab , I show your game in Apple TV , How do you save the game data?

**Comment by phoboslab** [comment]
Ejecta uses `NSUserDefaults` to store `LocalStorage` data. According to [this SO thread](http://stackoverflow.com/questions/32644622/can-i-use-nsuserdefaults-with-tvos) this works fine for up to 500kb:
