### ISSUE TITLE
context.font doesn't support "-" ?

### ISSUE THREAD

**Issue by finscn** [phoboslab/Ejecta#605]
My font named  "STHeitiSC-Medium" (a systme font in Chinese system)  , but no effect,  App used default font.

**Comment by phoboslab** [comment]
Not sure what's going on. The font name seems to be parsed correctly in Ejecta. It's handed over "as is" to the iOS `CTFontCreateWithName` function. I only get this warning message on my system (notice correct font name "STHeitiSC-Medium"):

>> CoreText performance note: Client called CTFontCreateWithName() using name "STHeitiSC-Medium" and got font with PostScript name "PingFangSC-Medium". For best performance, only use PostScript names when calling this API.

**Comment by finscn** [comment]
I see.
