### ISSUE TITLE
Edges from cropped drawImage bleed in when scaled

### ISSUE THREAD

**Issue by mrspeaker** [phoboslab/Ejecta#61]
I have a tileset that is 24x24 pixels. When I use the long version of drawImage (img, sx, sy, sw, sh, dx, dy, dw, dh) to crop and scale the tiles, then the edge of the surrounding tiles will "bleed" into the draw image call. 

I've tried with this simple test case: the top image is the "tileset" - 3 x 3 red and white tiles with a green circle (without background) as the center tile. When I chop out and scale up the circle (10 times) you can see the edges of the surrounding tiles: it's not a pixel that is leaking in, just a part of a pixel forming a square border. It's not present if I don't stretch it (and is not present in the browser):

![Render bug](http://i.imgur.com/8roIK.png)

The code to draw this is:

```
ctx.fillStyle = "#000";
ctx.fillRect(0,0,w,h);

// Non-scaled - entire tileset
ctx.drawImage(image, 0, 0);

// Scaled and chopped tile
ctx.drawImage(image, 
    24, 24,
    24, 24,
    5, 80, 
    24 * 10, 24 * 10);
```

**Comment by frankarendpoth** [comment]
Was there ever a solution found to this problem? I am having the same issue and would like to know if anyone has found a good way around this unwanted behavior.
