### ISSUE TITLE
Support for `image-rendering:pixelated` on canvas element.

### ISSUE THREAD

**Issue by amadeus** [phoboslab/Ejecta#610]
So Canvas 2d has support for `.imageSmoothingEnabled = false`, however in WebGL if we want nearest neighbor scaling we have to resort to internal WebGL functionality to accomplish it.

Chrome introduces a nice alternative solution to it, the CSS property `image-rendering:pixelated`.

It would be dope if we could apply this CSS prop to the canvas element before getting the context (at least) and have it apply to CSS transforms of the canvas element appropriately.

There are other values that can be applied to the `image-rendering` property so here's some info on the other acceptable values:

https://developer.mozilla.org/en-US/docs/Web/CSS/image-rendering

**Comment by phoboslab** [comment]
With the above commit, you can set the `image-rendering` style of the screen canvas at any time. This affects the up- **and** downscaling.

```js
canvas.style.imageRendering = 'pixelated'; // Nearest neighbor scaling
canvas.style.imageRendering = 'auto'; // Linear scaling (default)
```

**Comment by amadeus** [comment]
Oooh, fancy! Thanks!
