### ISSUE TITLE
Gamepad API not working under the tvOS Simulator ?

### ISSUE THREAD

**Issue by obiot** [phoboslab/Ejecta#612]
Hi, 

I have not tried yet with the real hardware (as I'm for now only working with the simulator), but whatever i'm doing i'm not having any event triggered while playing with the (simulated) Apple TV Remote.

when calling `var gamepads = navigator.getGamepads();`
all I have back is :
````javascript
gamepads: Array (4)
0 undefined
1 undefined
2 undefined
3 undefined
````

is this a known issue, or am I doing something wrong somewhere ?

(I'm using Ejecta 2.0, Xcode 7.3 and tvOS 9.2)

**Comment by phoboslab** [comment]
Works for me™. The Apple TV Remote is recognized about 1-2 sec after the app starts.

```js
setInterval(function(){
	var gamepads = navigator.getGamepads();
	console.log(gamepads);
}, 1000);

window.addEventListener('gamepadconnected', function(ev) {
	console.log('CONNECTED', ev);
});
```

Output:
```
2016-02-15 10:35:29.809 Ejecta-TV[14499:1313456] JS LOG: [undefined, undefined, undefined, undefined]
2016-02-15 10:35:30.825 Ejecta-TV[14499:1313456] JS LOG: [undefined, undefined, undefined, undefined]
2016-02-15 10:35:30.964 Ejecta-TV[14499:1313456] JS LOG: CONNECTED {gamepad: [object Gamepad], type: gamepadconnected, target: [object GamepadProvider], currentTarget: [object GamepadProvider], stopPropagation: [Function], preventDefault: [Function]}
2016-02-15 10:35:31.841 Ejecta-TV[14499:1313456] JS LOG: [[object Gamepad], undefined, undefined, undefined]
```

**Comment by obiot** [comment]
Weird, did u use the remote from the simulator or did u pair the "real" remote with it?

Thanks for checking anyway :)

**Comment by phoboslab** [comment]
I used the simulated remote. Can you even pair the real remote with the Simulator?

**Comment by obiot** [comment]
In theory you could I guess, since you can pair a gamepad ? I'll give it a shot later :)

**Comment by obiot** [comment]
so first I tried again tonight, and it's actually working.... I guess that I should upgrade to a more stable version of Xcode (i'm running a beta for now, might be the reason)

second, you cannot pair a real remote with the simulator, I tried and it's definitely a no-go :):):)

closing this ticket, sorry for bothering with this :)
