### ISSUE TITLE
Ejecta crashes in tapping 'siri' key on software keyboard.

### ISSUE THREAD

**Issue by homma-ge** [phoboslab/Ejecta#618]
Ejecta crashes after the following steps.

1. show keyboard, like a below code.
```
ejecta.getText( 'Highscore', 'Please enter your name', function(text) {
    console.log(text);
});
```

2. press 'siri' key on the keyboard.

3. Ejecta crashes at glDrawElements() call in EJBindingCanvasContextWebGL.m
```
EJ_BIND_FUNCTION(drawElements, ctx, argc, argv) {
	EJ_UNPACK_ARGV(GLenum mode, GLsizei count, GLenum type, GLint offset);
	
	scriptView.currentRenderingContext = renderingContext;
	renderingContext.needsPresenting = YES;
	
	glDrawElements(mode, count, type, EJ_BUFFER_OFFSET(offset));
	return NULL;
}
```

iOS 9.2.1
Ejecta latest ver (c7927a3)

**Comment by phoboslab** [comment]
Can't reproduce with a [simple test case (.zip)](http://phoboslab.org/crap/618-test-case.zip) on iPhone5S, iOS 9.2.1. Can you check if this crashes for you?

My guess is that Ejecta may not handle the OpenGL context change correctly in some cases. Can you provide a test case where this crashes?

**Comment by homma-ge** [comment]
Thank you. I tried the test case, but it didn't crash. 

Could you check if [this test case (.zip)](http://i2v.thephonetics.s3-website-ap-northeast-1.amazonaws.com/618-test-case_2.zip) crashes on your environment?
