### ISSUE TITLE
Is there a plan for supporting WebGL in the roadmap of ImpactJS ?

### ISSUE THREAD

**Issue by finscn** [phoboslab/Ejecta#620]
I try to develop 2D Game with WebGL , but pixi.js is too big and too complex. and it's not  a game-framework (just render framework) 

I'm also watching some projects about  WebGL for 2D  ( like https://github.com/gameclosure/webgl-2d ) , but they are not good enough . 

I like ImpactJS, it's light , fast and easy to use. 

Is there a plan for supporting WebGL (just for 2D Game) in the roadmap of ImpactJS ?

**Comment by phoboslab** [comment]
Yes :) In fact, I'm aiming to make Impact 2 WebGL only.

**Comment by finscn** [comment]
Is it free for Impact 1.x user ?

**Comment by phoboslab** [comment]
No, it's a complete rewrite, so it will be a paid upgrade for existing users.

**Comment by finscn** [comment]
OK. I will be waiting for 2.0.
