### ISSUE TITLE
'ANGLE_instanced_arrays' is supported in Ejecta gl.extensions?

### ISSUE THREAD

**Issue by homma-ge** [phoboslab/Ejecta#622]
I wanna use geometry instancing, such as 'http://threejs.org/examples/webgl_buffergeometry_instancing.html'.

But gl.getExtension( 'ANGLE_instanced_arrays' ) returns 'undefined' on Ejecta.
Is this not hardware supported?

Thanks.

**Comment by phoboslab** [comment]
Test case: http://phoboslab.org/files/ejecta-instanced-arrays.zip
Happily runs with 60fps on my iPhone5s.

Screenshot from Simulator:
<img width="432" alt="screen shot 2016-02-28 at 12 31 59" src="https://cloud.githubusercontent.com/assets/443987/13378943/3f70f0f0-de17-11e5-89d6-6d68224b535a.png">

**Comment by takaando-dtc** [comment]
:+1:

**Comment by homma-ge** [comment]
Thanks for your great support!
