### ISSUE TITLE
gamepadconnected & gamepaddisconnected  have been removed in Browser

### ISSUE THREAD

**Issue by finscn** [phoboslab/Ejecta#623]
In new Browser , Gamepad is like  Keyboard and Mouse , no  connected & disconnected events.

Developers   just  need to  read the data of Gamepad via window.navigator.getGamepads in every game tick.

This is  good news.

**Comment by phoboslab** [comment]
Do you have any reference for that? The latest Gamepad API Spec still mentions these events:
https://www.w3.org/TR/gamepad/#event-gamepadconnected

Besides, you don't have to listen to these events in Ejecta either. You can poll `navigator.getGamepads` regardless if one is connected or not.

**Comment by finscn** [comment]
No. I can't find any document about it. But I test it.

**Comment by ericjbasti** [comment]
Even if they should remove the events from the spec (which I doubt would ever happen). These events are extremely valuable to have. Knowing that a controller has connected or disconnected without needing to check through getGamepads every tick is very helpful. Plus it coincides with Apples internal GCController notifications.

**Comment by phoboslab** [comment]
Yeah, I don't think it makes sense to remove this. Closing for now.
