### ISSUE TITLE
'OES_texture_float_linear' and 'OES_element_index_uint' are supported in Ejecta gl.extensions?

### ISSUE THREAD

**Issue by homma-ge** [phoboslab/Ejecta#624]
I wanna use geometry instancing, such as http://threejs.org/examples/webgl_buffergeometry_instancing_billboards.html

Test case:
https://s3-ap-northeast-1.amazonaws.com/i2v.thephonetics/ejecta_testcase_160315.zip

On Ejecta, this test-case shows the  below WARNING and has a lower FPS.
'THREE.WebGLRenderer: OES_texture_float_linear extension not supported.'
'THREE.WebGLRenderer: OES_element_index_uint extension not supported.'

On Safari, it's a better FPS.

Instancing is very powerful, so I hope these extensions will be supported.

Thanks.

**Comment by phoboslab** [comment]
I've added support for the `OES_element_index_uint extension`.

The `OES_texture_float_linear` extension is not available on iOS natively. See https://developer.apple.com/library/ios/documentation/DeviceInformation/Reference/iOSDeviceCompatibility/OpenGLESPlatforms/OpenGLESPlatforms.html - maybe ThreeJS could use `half_float_linear` instead?
