### ISSUE TITLE
Bug of globalCompositeOperation 

### ISSUE THREAD

**Issue by finscn** [phoboslab/Ejecta#625]
test code : 
```js

        // There is an offScreenCanvas , size =  600 * 600 (Big);
        // Fill with Blue ;
        var ctx = offScreenCanvas.getContext("2d");
        ctx.fillStyle = "blue";
        ctx.fillRect(0, 0, offScreenCanvas.width, offScreenCanvas.height);

        // Use globalCompositeOperation to create a small red rect , size = 50 * 50.
        ctx.globalCompositeOperation = 'source-in';
        ctx.fillStyle = "red";
        ctx.fillRect(0, 0, 50, 50);

        // context  belongs ScreenCanvas
        context.globalCompositeOperation = "lighter";
        context.drawImage(offScreenCanvas, 10, 10);

        //  BUG :
        // the Lighter region is  big  (600 * 600)

```

**Comment by phoboslab** [comment]
What's the expected outcome?

You're drawing the whole `offscreenCanvas` onto the screen canvas, all its 600x600 pixels. Keep in mind that the screen canvas is essentially treated as "filled with black" initially. Even though, I think the `lighter` blend mode is supposed to draw _over_ transparent pixels. See https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation

**Comment by finscn** [comment]
The lighter  region  in Chrom and Safari  is  small ( 50 * 50 ).

The code
```
        ctx.globalCompositeOperation = 'source-in';
        ctx.fillStyle = "red";
        ctx.fillRect(0, 0, 50, 50);
```
has  "crop" the offScreenCanvas  valid region to 50*50 .

**Comment by finscn** [comment]
Maybe this bug is about #365  ? 
the OpenGL  is too hard to  implement the Canvas globalCompositeOperation  perfect  ?

**Comment by phoboslab** [comment]
Sorry, I misunderstood. I thought `context.globalCompositeOperation = "lighter";` was causing the problem, not the `source-in` blend mode. So, yeah. `source-in` is not properly supported. We'd need to draw over the whole screen to "erase" what's there and not covered by the new content.

I'd think that Implementing all globalCompositeOperations accurately would make the whole system a good deal slower. I don't have that much interest in doing so. The usefulness of some of the composite ops is pretty limited, imho.

Previous discussion: https://github.com/phoboslab/Ejecta/issues/589
