### ISSUE TITLE
Possible to get it running on Windows?

### ISSUE THREAD

**Issue by Dillybob92** [phoboslab/Ejecta#627]
Hey,

This project looks amazing. I am creating a relatively large game (100k+ LoC) and currently using Electron to build for windows / .exe.

Problem is, RequestAnimationFrame inside Chromium get's disabled if a window is minimized :(. Since my game's physics's are tied to RAF. And my game is multiplayer and instance based (physics are updated all the time from the server -> player). I need the game's RAF to be running 24/7. I believe if I can get my canvas element inside ejecta and run this on windows it would not only boost my performance, but squash that RAF bug.

It would also remove all HTML elements and stuff, but I can code that stuff inside canvas later on. So just curious do you think this would be the right thing to do for my issue and I know it would be a huge performance increase.  I'm just not sure how I can get it to work on windows

--Nick

**Comment by amadeus** [comment]
I don't think Ejecta is a solution you'd want to fix this issue. It's designed to be compiled with iOS.

You'd have to essentially write your own version of Ejecta to do this, I don't think there's much from this project you could easily re-use.

However, there's probably a fairly simple solution to your problem, there are page show/hide events that will get fired, and you could use those to switch to a setTimeout based system to just continue calculating physics.

**Comment by Dillybob92** [comment]
Aww I see. Yeah, but not sure if it's possible to run the physics without RAF. It would be really weird / glitchy? But, I really think Ejecta would be really popular on the windows platform. Although, I think the argument is it's not really needed because the performance is so good already, but man, the feeling of only a canvas app would actually motivate me to write some gui stuff inside canvas :)

 In any event, thanks I am using Electron for my app and found this: https://github.com/atom/electron/issues/4925 So maybe there is hope! I will try the physics update thing when browser is minimized using the events

**Comment by amadeus** [comment]
I mean, I guess it depends on what game engine you are using? But literally you would want to do something akin to:

```js
var updatePhysics = function(){
    // Update all your physics here
    setTimeout(updatePhysics, 1000 / 60);
};

updatePhysics();
```

That's a very simple run loop using `setTimeout` that shouldn't stop when the app is mimimized. Obviously in context with your app/game it would look/work very differently.

**Comment by Dillybob92** [comment]
Oh, yeah well, I'm using Phaser and their physics go through their own `update` function so that's kind of why I am not sure if it would work.  I will try your methodology though and see what I can come up with.  Sorry for the derailment of this thread :P

**Comment by amadeus** [comment]
Check out this thread for more information regarding Phaser: http://www.html5gamedevs.com/topic/10847-gamestagedisablevisibilitychange-not-working/

**Comment by phoboslab** [comment]
FYI: Most Browsers limit `setInterval`/`setTimeout` calls to 1/sec for background tabs as well. See: http://stackoverflow.com/questions/15871942/how-do-browsers-pause-change-javascript-when-tab-or-window-is-not-active
