### ISSUE TITLE
My AppleTV Game powered by Ejecta has been available and ready for sale.

### ISSUE THREAD

**Issue by finscn** [phoboslab/Ejecta#628]
Update: 

My AppleTV game  Jump Fatty TV is available and ready for sale now. 
Search "Jump Fatty"  please.

===========================

My AppleTV Game powered by Ejecta has been testing on Testflight.

Welcome to test my AppleTV game. ( There is an iOS version  too).
Leave your Apple ID (email) ,  I'll send you an Invitation .

Thanks very much.

Screenshots:

![4in1](https://cloud.githubusercontent.com/assets/288367/14579588/d3f8ddce-03e1-11e6-9ab8-b505305d7865.png)

**Comment by lordnasty** [comment]
Awesome!

**Comment by lordnasty** [comment]
my apple id: spaturno@gmail.com

**Comment by phoboslab** [comment]
Closing this now. The [Made with Ejecta](https://github.com/phoboslab/Ejecta/issues/581) will stick around longer - you may want to post it there instead.
