### ISSUE TITLE
EXC_BAD_ACCESS in glTexImage2D()

### ISSUE THREAD

**Issue by homma-ge** [phoboslab/Ejecta#629]
Ejecta sometimes crashes in EJBindingCanvasContextWebGL.m, line 1468.

`
glTexImage2D(target, level, format, width, height, 0, format, type, nulled);
`

This crash often occurs in legacy devices such as iPad2 and iPad mini (A5 processor).

I don't have testcase because this is a little Intricate.
Do you have any advice about this issue?

Thanks.

**Comment by phoboslab** [comment]
Hard to say without more info. I would guess that the call to `calloc()` right before it fails to allocate memory. This would make sense as it, as you report, only occurs on devices with less RAM.

**Comment by homma-ge** [comment]
Thanks for your advice. I've adjusted multiple resource loading timing, then it's worked better.
