### ISSUE TITLE
Ejecta 2.1

### ISSUE THREAD

**Issue by obiot** [phoboslab/Ejecta#630]
Hi, sorry to open a ticket just for this, but do you plan to "officialize" a 2.1 version any time soon ? 
2.0 has been released almost 6 months ago, lots of fixes and useful improvements have been added since then, and it would be nice to have an actual release point with them :)

thanks !
Oliver

**Comment by phoboslab** [comment]
Thanks for the reminder to put out releases :)

I think I want to wait for the [new Typed Array API](https://github.com/WebKit/webkit/blob/master/Source/JavaScriptCore/API/JSTypedArray.h#L48) to arrive in iOS, so we have better WebGL performance again. It should come with iOS 10 - which is slated for release at WWDC 2016 in mid June.

**Comment by obiot** [comment]
makes sense ! thanks for the feedback, and looking forward to it :)

**Comment by aking** [comment]
Looks like the new Typed Array API has been added to iOS!

https://developer.apple.com/library/prerelease/content/releasenotes/General/iOS10APIDiffs/Objective-C/JavaScriptCore.html

**Comment by darknoon** [comment]
@phoboslab Are you working on adopting the new API or should I work on a PR?

**Comment by phoboslab** [comment]
Working on it. There's a bunch of deprecation warnings when updating to the iOS10 SDK that I want to work through first.

**Comment by phoboslab** [comment]
With the recent commits, Ejecta now uses JSCs built-in Typed Array API. This also means that you need the new iOS 10 SDK (i.e. XCode Beta) to compile it.

I'll wait a little while longer to see if there are any issues with this change before I put out the 2.1 tag. Let me know if you have any problems!

**Comment by obiot** [comment]
Is this also already support by the new beta tvOS ?

**Comment by obiot** [comment]
*supportED :)

**Comment by phoboslab** [comment]
Yes, this also run on tvOS 10.

**Comment by obiot** [comment]
awesome, I definitely need to install the last beta XDK.

This said, it would really be useful to have an intermediate version like 2.0.1 for example, as one one side we then have version 2.0, that lacks all the fixes added to the master branch, and then the coming 2.1 that requires iOS10 and won't be "usable" before September from a production point of view.

**Comment by obiot** [comment]
with both tvOS10 and Xcode 8 being officially released, time for a former release :):):)

**Comment by phoboslab** [comment]
http://impactjs.com/blog/2016/09/ejecta-2-1 :)
