### ISSUE TITLE
Maybe there is a bug at EJPath.mm

### ISSUE THREAD

**Issue by finscn** [phoboslab/Ejecta#633]
https://github.com/phoboslab/Ejecta/blob/master/Source/Ejecta/EJCanvas/2D/EJPath.mm#L299

```
	float span = antiClockwise
		? (startAngle - endAngle) *-1
		: (endAngle - startAngle);
```

Because that  ```(startAngle - endAngle) * -1 === endAngle - startAngle ``` ,
the line 299 equals to :
```
float span = antiClockwise ? (endAngle - startAngle) : (endAngle - startAngle);
```
span  always equals to  endAngle - startAngle.

Is there a bug ?

**Comment by phoboslab** [comment]
Nice find, thanks!
