### ISSUE TITLE
What's the lowest latency way to get the timestamp of a touch?

### ISSUE THREAD

**Issue by fictorial** [phoboslab/Ejecta#634]
My game uses a time-based mechanic for determining accuracy of a player's shot.  Think of one of those swing power meters in many golf games.  My current strategy is to stop the animation of the meter upon touch start.  But, there's a decent amount of latency.  I don't see a timestamp associated with the touch information.  I can add it but I want to make sure there's not something I'm missing already.

**Comment by fictorial** [comment]
Nevermind! It was really trivial to add.

```
    jsTimestampName = JSStringCreateWithUTF8CString("timestamp");
//...
    JSStringRelease( jsTimestampName );
//...
        JSValueRef timestamp = JSValueMakeNumber(ctx, touch.timestamp);
//...
        JSObjectSetProperty( ctx, jsTouch, jsTimestampName, timestamp, kJSPropertyAttributeNone, NULL );
//...
```

and usage:

```
document.addEventListener( 'touchstart', function( ev ) {
    console.log('touch start at ' + ev.touches[0].timestamp);
});
```

**Comment by phoboslab** [comment]
Reopening. This should probably be implemented in Ejecta directly. Thanks!

**Comment by phoboslab** [comment]
The above commit adds a `timestamp` to all events. E.g. for touch input:

```js
document.addEventListener( 'touchstart', function( ev ) {
    console.log('touch start at ' + ev.timestamp);
});
```
