### ISSUE TITLE
WebGL example doesn't render (black screen)

### ISSUE THREAD

**Issue by darknoon** [phoboslab/Ejecta#636]
Steps to repro:
- Download latest master
- Unzip http://phoboslab.org/files/Ejecta-ThreeJS-CubeMap.zip as App/
- Run

Expected result:
Demo renders

Actual result: 
Black screen

Discussion:
It appears that the framebuffer is getting unbound in `-[EJCanvasContextWebGLScreen resizeToWidth:height:]`

Fixing it seems to be a touch involved, but I started messing around with keeping `EJ_WEBGL_DEFAULT_RENDERBUFFER` set in `boundRenderbuffer` and the same for the framebuffer to try to have it get fixed in `-prepare`, but I'm not familiar with all of the state management code here.

**Comment by phoboslab** [comment]
Thanks!
