### ISSUE TITLE
 Excuse me 

### ISSUE THREAD

**Issue by longqingyang** [phoboslab/Ejecta#639]
Hello, do you have the plan to support ARC Ejecta?

**Comment by phoboslab** [comment]
No. We decided against it for performance reasons. See #113

**Comment by longqingyang** [comment]
OK~ Thank you !  There is a problem, how to dynamically change the the frame  of  EJJavaScriptView ？(Such as amplification, reduce operation)  
 I tried to change  the frame, but there was no response !   ~_~

**Comment by phoboslab** [comment]
What exactly did you try? Can you show some code? `setFrame` should work, afaik.

**Comment by phoboslab** [comment]
Closing for lack of info (and bad title).
