### ISSUE TITLE
Closure JS library fails with "Your browser does not support creating new documents"

### ISSUE THREAD

**Issue by bovine** [phoboslab/Ejecta#641]
Javascript libraries that have been processed by Closure JS compiler fail to load because of an XML document failure in its `goog.dom.xml.createDocument` function.

https://github.com/google/closure-library/blob/9546e0fa38ef57fa16ecb958244149c680819bcc/closure/goog/dom/xml.js#L87

The error message "Your browser does not support creating new documents" is thrown, causing failure to load for that library. As a workaround, I've simply commented out that throw and am able to load the rest of that library though.

It might be worthwhile to provide some shims in Ejecta.js to implement `document.implementation.createDocument` at least as an empty stub, or ideally as something minimally functional for loading XML.

**Comment by phoboslab** [comment]
Ejecta doesn't have a DOM library, so parsing, creating and manipulating documents (XML, HTML) isn't something we could easily do. We could implement a DOM library, but I don't really see the point, we we're not able to render a document.

Parsing XML could be useful, though...
