### ISSUE TITLE
iOS 9 doesn't support "displayLink.preferredFramesPerSecond"

### ISSUE THREAD

**Issue by finscn** [phoboslab/Ejecta#647]
I hope Ejecta could support the Last version of iOS and  has the compatibility for previous version.

Giving up iOS 9 is  unwise now.

I add the code for this request at EJJavaScriptView.m : 
```
    if (EJECTA_SYSTEM_VERSION_LESS_THAN(@"10")){
        [displayLink setFrameInterval:1];
    }else{
        displayLink.preferredFramesPerSecond = 60;
    }
```

**Comment by phoboslab** [comment]
You can still compile for iOS 9 without any code changes. Just set the _iOS Deployment Target_ to 9.0 and leave the _Base SDK_ at 10.0.

**Comment by phoboslab** [comment]
Turns out you're right :) Since iOS9 doesn't support `preferredFramesPerSecond` it would crash the app.

The simplest solution however, is just to remove this line completely and leave it at the OS default!

**Comment by finscn** [comment]
this commit https://github.com/phoboslab/Ejecta/commit/891fa212a772fcbf971fb1803127f909f679e21f
can't run under iOS 9 too.
