### ISSUE TITLE
Crashes on iOS 9 device

### ISSUE THREAD

**Issue by dedoubleyou1** [phoboslab/Ejecta#649]
It runs perfectly on my iOS 10 device but it crashes on my iOS 9 device.

Ejecta is crashing in EJ_BIND_GET in EJBindingImageData.m on the following line for me:

dataArray = JSObjectMakeTypedArray(ctx, kJSTypedArrayTypeUint8ClampedArray, byteLength, NULL);

It's crashing with the following message:
Dyld Message: Symbol not found: _JSObjectMakeTypedArray

**Comment by sleep2death** [comment]
Current version is iOS 10 ONLY, checkout older version to run on iOS9 devices

**Comment by phoboslab** [comment]
Yep. Ejecta 2.1 only runs on iOS 10 and newer. I've updated the [Ejecta project page](http://impactjs.com/ejecta) to reflect this. Use the [2.0 release](https://github.com/phoboslab/Ejecta/releases/tag/v2.0) if you need compatibility with older iOS versions.
