### ISSUE TITLE
`glIsEnabled(...)` shouldn't be a 'direct' bind?

### ISSUE THREAD

**Issue by nikki93** [phoboslab/Ejecta#650]
Not sure but I think `glIsEnabled(...)` shouldn't be bound with `EJ_BIND_FUNCTION_DIRECT(...)` because it should return a value? I think the Mozilla page for it might be erroneous.

See:
https://github.com/phoboslab/Ejecta/blob/b4cbeebe10bd9cb1d188db73d56b9450d79a3f47/Source/Ejecta/EJCanvas/WebGL/EJBindingCanvasContextWebGL.m#L1237
https://github.com/phoboslab/Ejecta/blob/b4cbeebe10bd9cb1d188db73d56b9450d79a3f47/Source/Ejecta/EJCanvas/WebGL/EJBindingCanvasContextWebGL.m#L160

**Comment by phoboslab** [comment]
This was a bug in Ejecta. glIsEnabled should of course return a value - otherwise it would be pretty much useless. Thanks for reporting!
