### ISSUE TITLE
Why the performance is very bad with PIXI.js v4 in Ejecta ?

### ISSUE THREAD

**Issue by finscn** [phoboslab/Ejecta#653]
Why the performance is very bad with PIXI.js v4 in Ejecta ?

I  port the the http://www.goodboydigital.com/pixijs/bunnymark/  to Ejecta and Safari for iOS .

Test in Safari for iOS ,everything is OK , and the FPS is about 50.
But in Ejecta , just 5 FPS.

Why ?  

this is test case : 

[bunnymark.zip](https://github.com/phoboslab/Ejecta/files/530594/bunnymark.zip)

put the "bunnymark" folder  into  App/example/

and  index.js is 
```
ejecta.include("example/bunnymark/e-bunnymark.js");
```

test.html is for Safari  or other browser .

**Comment by phoboslab** [comment]
Without having looked at the source, I would guess that this demo is performance bound by JavaScript, not  by rendering.

Remember, Ejecta can't use the JavaScript JIT. If there's a lot of stuff to be processed for each sprite, it will run slower in Ejecta than in the browser. I don't think there's anything we can do about it :/

**Comment by finscn** [comment]
Why is there no JIT in Ejecta  ?
And  Is calling Native method  in JS   one reason of bad performance?

**Comment by phoboslab** [comment]
It's not allowed by Apple. JSC can't allocate writeable+executable memory, so it can't compile the JavaScript code; it has to be interpreted.

There is some performance penalty for calling a native method from JavaScript, but it's fairly insignificant. The bottleneck is the absence of the JIT.

**Comment by finscn** [comment]
:'(     it's a pity. 
I think maybe it's time to move to Cordova .
I've write many plugins & extensions of Ejecta , But now, they become uselessness , I want to cry ... tears....
