### ISSUE TITLE
Cannot submit app due to NSPhotoLibraryUsageDescription issue.

### ISSUE THREAD

**Issue by homma-ge** [phoboslab/Ejecta#655]
When I submit my app with Ejecta on iOS 10, I received the message below from Apple. (Nevertheless I don't access photo library)

> This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSPhotoLibraryUsageDescription key with a string value explaining to the user how the app uses this data.

Does Ejecta use photo library? If so, can I disable or remove it?
Also, please refer to the [similar issue](https://github.com/ReactiveCocoa/ReactiveCocoa/issues/3190)

[Apple developer forum](https://forums.developer.apple.com/thread/62229)

Thanks.

**Comment by homma-ge** [comment]
EJBindingImagePicker seems to access photo library.

**Comment by phoboslab** [comment]
This sucks.  It would be nice to have the photo picker automatically disabled when the `NSPhotoLibraryUsageDescription` key is not present in the plist, but I guess Apple would still reject it, if it's compiled in!? Guarding it with an `#ifdef` is the only solution I can think of.

As a workaround, you can just delete the `Source/Ejecta/EJUtils/EJBindingImagePicker.h` and `EJBindingImagePicker.m` files and recompile. They're not referenced anywhere else.

**Comment by homma-ge** [comment]
> As a workaround, you can just delete the Source/Ejecta/EJUtils/EJBindingImagePicker.h and EJBindingImagePicker.m files and recompile. They're not referenced anywhere else.

I have avoided this reject by removing EJBindingImagePicker.h/.m and recompiling.  
Thanks.

**Comment by AlexBezuska** [comment]
I had the same issue and tried deleting `Source/Ejecta/EJUtils/EJBindingImagePicker.h` and `Source/Ejecta/EJUtils/EJBindingImagePicker.m` but now I get 
```
clang: error: no such file or directory: /Users/alexbezuska/projects/scurry/ios/Source/Ejecta/EJUtils/EJBindingImagePicker.m

clang: error: no input files```
