### ISSUE TITLE
On iPad pro, Ejecta freezes when returning from the background.

### ISSUE THREAD

**Issue by homma-ge** [phoboslab/Ejecta#660]
environment:
- IPad Pro 2nd generation 10.5 or 12.9 (latest model) refresh rate is 120hz
- IOS 10.3.2
- Run Ejecta sample index.js.

procedure:
- 1. Launch the application (index.js on Ejecta).
- 2. Press the Home button to move the application to the background.
- 3. Return to the application again.

behavior:
- At this time, the picture of the application freezes for 5 seconds or longer.
- After that, the application starts to move as usual.

frequency of occurrence
- 20/20

If you have a test code, please send it as it will be executed here.

**Comment by homma-ge** [comment]
In this state, it seems that the following function is not called.

EJTimer.m
- (void)update {
	for( NSNumber *timerId in [timers allKeys]) {
		EJTimer *timer = [timers[timerId] retain];
		[timer check];
		
		if( !timer.active ) {
			[timers removeObjectForKey:timerId];
		}
        [timer release];
	}
}

**Comment by homma-ge** [comment]
iPad pro's refresh rate is 120hz.

**Comment by homma-ge** [comment]
pause() and resume() of run loop works well.  But the above run() is not called for 5 mins.

**Comment by homma-ge** [comment]
I have confirmed that the following code can fix this problem. Can you confirm it?

I destroy displayLink every time pause() and create it again every time resume(). Is there any problem with this change?
`
- (void)pause {
	if( isPaused ) { return; }
	
	[windowEventsDelegate pause];
	[displayLink removeFromRunLoop:NSRunLoop.currentRunLoop forMode:NSDefaultRunLoopMode];

	// CHANGED
	// Remove from display link
	[displayLink invalidate];
	[displayLink release];
    
	[screenRenderingContext finish];

	[AVAudioSession.sharedInstance setActive:NO error:NULL];
	[openALManager beginInterruption];
	
	isPaused = true;
}

- (void)resume {
	if( !isPaused ) { return; }
	
	[windowEventsDelegate resume];
	[EAGLContext setCurrentContext:glCurrentContext];
    
	// CHANGED
	displayLink = [[CADisplayLink displayLinkWithTarget:proxy selector:@selector(run:)] retain];
	[displayLink addToRunLoop:[NSRunLoop currentRunLoop] forMode:NSDefaultRunLoopMode];

	[AVAudioSession.sharedInstance setActive:YES error:NULL];
	[openALManager endInterruption];
	
	isPaused = false;
}
`

**Comment by phoboslab** [comment]
Interesting. I wonder why this only seems to happen on the iPad Pro 2 - maybe a race condition with the higher refresh rate!?

In any case, removing the `CADisplayLink` from the run loop on `pause` and adding it back again on `resume` might be the wrong approach anyway. Looking through the docs, I found that `CADisplayLink` actually has a `.paused` attribute.

Can you please check if this fixes your problem? It seems to work fine on my test devices.

```objc
- (void)pause {
	if( isPaused ) { return; }
	
	[windowEventsDelegate pause];
	displayLink.paused = YES;
	[screenRenderingContext finish];

	[AVAudioSession.sharedInstance setActive:NO error:NULL];
	[openALManager beginInterruption];
	
	isPaused = true;
}

- (void)resume {
	if( !isPaused ) { return; }
	
	[windowEventsDelegate resume];
	[EAGLContext setCurrentContext:glCurrentContext];
	displayLink.paused = NO;

	[AVAudioSession.sharedInstance setActive:YES error:NULL];
	[openALManager endInterruption];
	
	isPaused = false;
}
```

**Comment by homma-ge** [comment]
It's fixed!

> Can you please check if this fixes your problem? It seems to work fine on my test devices.

Thanks.
